const cycleCountReportingIndicators = {
  totalCount: {
    titleLabel: 'react.cycleCount.indicators.cardTitle.totalCount.label',
    defaultTitle: 'Total count physical inventory',
    numberType: 'number',
    subtitleLabel: 'react.cycleCount.indicators.cardSubtitle.inMyInventory.label',
    defaultSubtitle: 'in my inventory',
    infoLabel: 'react.cycleCount.indicators.cardInfo.totalCount.label',
    defaultInfo: 'Total physical inventory count',
  },
  itemsCounted: {
    titleLabel: 'react.cycleCount.indicators.cardTitle.itemsCounted.label',
    defaultTitle: 'Items counted',
    numberType: 'number',
    subtitleLabel: 'react.cycleCount.indicators.cardSubtitle.inMyInventory.label',
    defaultSubtitle: 'in my inventory',
    infoLabel: 'react.cycleCount.indicators.cardInfo.itemsCounted.label',
    defaultInfo: 'Total items counted',
  },
  targetProgress: {
    titleLabel: 'react.cycleCount.indicators.cardTitle.targetProgress.label',
    defaultTitle: 'Target progress',
    numberType: 'number',
    subtitleLabel: 'react.cycleCount.indicators.cardSubtitle.itemsCounted.label',
    defaultSubtitle: 'items counted',
    infoLabel: 'react.cycleCount.indicators.cardInfo.targetProgress.label',
    defaultInfo: 'Shows how far along the count progress is',
    showPercentSign: true,
  },
  notFinishedItems: {
    titleLabel: 'react.cycleCount.indicators.cardTitle.notFinishedItems.label',
    defaultTitle: 'Not finished items',
    numberType: 'number',
    subtitleLabel: 'react.cycleCount.indicators.cardSubtitle.inMyInventory.label',
    defaultSubtitle: 'in my inventory',
    infoLabel: 'react.cycleCount.indicators.cardInfo.notFinishedItems.label',
    defaultInfo: 'Items remaining to be counted or processed',
  },
  inventoryLoss: {
    titleLabel: 'react.cycleCount.indicators.cardTitle.inventoryLoss.label',
    defaultTitle: 'Inventory loss',
    firstSubtitleLabel: 'react.cycleCount.indicators.cardSubtitle.countedLess.label',
    defaultFirstSubtitle: 'counted less than in system',
    secondSubtitleLabel: 'react.cycleCount.indicators.cardSubtitle.overallLost.label',
    defaultSecondSubtitle: 'overall $ lost',
    infoLabel: 'react.cycleCount.indicators.cardInfo.inventoryLoss.label',
    defaultInfo: 'Inventory loss',
  },
};

export default cycleCountReportingIndicators;
