const ALL_PRODUCTS_TAB = 'ALL_PRODUCTS';
const TO_COUNT_TAB = 'TO_COUNT';
const TO_RESOLVE_TAB = 'TO_RESOLVE';
const TO_APPROVE_TAB = 'TO_APPROVE';

const PRODUCTS_TAB = 'PRODUCTS';
const INVENTORY_TRANSACTIONS_TAB = 'INVENTORY_TRANSACTIONS';
const INDICATORS_TAB = 'INDICATORS';

export {
  ALL_PRODUCTS_TAB,
  INDICATORS_TAB,
  INVENTORY_TRANSACTIONS_TAB,
  PRODUCTS_TAB,
  TO_APPROVE_TAB,
  TO_COUNT_TAB,
  TO_RESOLVE_TAB,
};
