const columns = {
  EXPIRATION_DATE: 'inventoryItem.expirationDate',
  QUANTITY_COUNTED: 'quantityCounted',
  QUANTITY_RECOUNTED: 'quantityRecounted',
  BIN_LOCATION: 'binLocation',
  ROOT_CAUSE: 'rootCause',
  COMMENT: 'comment',
  LOT_NUMBER: 'inventoryItem.lotNumber',
  COUNT_DIFFERENCE: 'countDifference',
  RECOUNT_DIFFERENCE: 'recountDifference',
  ACTIONS: 'actions',
  SELECTED: 'selected',
  DATE_LAST_COUNTED: 'dateLastCount',
  PRODUCT: 'product',
  CATEGORY_NAME: 'category.name',
  CATEGORY: 'category',
  INTERNAL_LOCATIONS: 'internalLocations',
  TAGS: 'tags',
  PRODUCT_CATALOGS: 'productCatalogs',
  ABC_CLASS: 'abcClass',
  QUANTITY_ON_HAND: 'quantityOnHand',
  STATUS: 'status',
  ALIGNMENT: 'alignment',
  TRANSACTION_TYPE: 'cycleCount.transactionType',
  RECORDED: 'cycleCount.dateRecorded',
  TRANSACTION_ID: 'cycleCount.transactionNumber',
  QTY_BEFORE: 'blindCount.quantityOnHand',
  QTY_AFTER: 'verificationCount.quantityCounted',
  DIFFERENCE: 'difference',
  ROOT_CAUSES: 'verificationCount.varianceReasonCode',
  COMMENTS: 'verificationCount.varianceComment',
  ASSIGNEE: 'assignee',
  DEADLINE: 'deadline',
  INVENTORY_ITEMS: 'inventoryItems',
};

export default columns;
