const ALL_PRODUCTS_TAB = 'ALL_PRODUCTS';
const TO_COUNT_TAB = 'TO_COUNT';
const TO_RESOLVE_TAB = 'TO_RESOLVE';
const TO_APPROVE_TAB = 'TO_APPROVE';

export {
  ALL_PRODUCTS_TAB,
  TO_APPROVE_TAB,
  TO_COUNT_TAB,
  TO_RESOLVE_TAB,
};
