export default {
  REQUESTED: 'REQUESTED',
  COUNTING: 'COUNTING',
  COUNTED: 'COUNTED',
  INVESTIGATING: 'INVESTIGATING',
  READY_TO_REVIEW: 'READY_TO_REVIEW',
  REVIEWED: 'REVIEWED',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  CREATED: 'CREATED',
};
