const CycleCountItemStatus = {
  READY_TO_COUNT: 'READY_TO_COUNT',
  COUNTING: 'COUNTING',
  COUNTED: 'COUNTED',
  INVESTIGATING: 'INVESTIGATING',
  READY_TO_REVIEW: 'READY_TO_REVIEW',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELED: 'CANCELED',
};
export default CycleCountItemStatus;
