const discrepancyReasonCode = {
  MISSING_TRANSACTION: 'MISSING_TRANSACTION',
  MISCOUNTED: 'MISCOUNTED',
  INVENTORY_FOUND: 'INVENTORY_FOUND',
  INVENTORY_EXPIRED: 'INVENTORY_EXPIRED',
  INVENTORY_LOST: 'INVENTORY_LOST',
};

export default discrepancyReasonCode;
