const locationType = {
  DEPOT: 'DEPOT',
  ZONE: 'ZONE',
  BIN_LOCATION: 'BIN_LOCATION',
  INTERNAL: 'INTERNAL',
  DISPENSARY: 'DISPENSARY',
  WARD: 'WARD',
  SUPPLIER: 'SUPPLIER',
  DONOR: 'DONOR',
  CONSUMER: 'CONSUMER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  DISPOSAL: 'DISPOSAL',
  VIRTUAL: 'VIRTUAL',
};

export default locationType;
