const RequisitionStatus = {
  CREATED: 'CREATED',
  EDITING: 'EDITING',
  VERIFYING: 'VERIFYING',
  PICKING: 'PICKING',
  PICKED: 'PICKED',
  PENDING: 'PENDING',
  CHECKING: 'CHECKING',
  ISSUED: 'ISSUED',
  RECEIVED: 'RECEIVED',
  CANCELED: 'CANCELED',
  DELETED: 'DELETED',
  ERROR: 'ERROR',
  DISPATCHED: 'DISPATCHED',
  REQUESTED: 'REQUESTED',
  OPEN: 'OPEN',
  FULFILLED: 'FULFILLED',
  REVIEWING: 'REVIEWING',
  CONFIRMING: 'CONFIRMING',
};

export default RequisitionStatus;
