const StockMovementStatus = {
  CREATED: 'CREATED',
  REQUESTING: 'REQUESTING',
  REQUESTED: 'REQUESTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  VALIDATING: 'VALIDATING',
  VALIDATED: 'VALIDATED',
  APPROVED: 'APPROVED',
  PICKING: 'PICKING',
  PICKED: 'PICKED',
  CHECKING: 'CHECKING',
  CHECKED: 'CHECKED',
  PACKED: 'PACKED',
  REVIEWING: 'REVIEWING',
  DISPATCHED: 'DISPATCHED',
  CANCELED: 'CANCELED',
  REJECTED: 'REJECTED',
};

export default StockMovementStatus;
