Project openboxes {
  database_type: 'MySQL'
  Note: 'Data model for latest development version of OpenBoxes'
}

Table "DATABASECHANGELOG" {
  "ID" varchar(63) [not null]
  "AUTHOR" varchar(63) [not null]
  "FILENAME" varchar(200) [not null]
  "DATEEXECUTED" datetime [not null]
  "MD5SUM" varchar(32) [default: NULL]
  "DESCRIPTION" varchar(255) [default: NULL]
  "COMMENTS" varchar(255) [default: NULL]
  "TAG" varchar(255) [default: NULL]
  "LIQUIBASE" varchar(10) [default: NULL]

Indexes {
  (ID, AUTHOR, FILENAME) [pk]
}
}

Table "DATABASECHANGELOGLOCK" {
  "ID" int(11) [pk, not null]
  "LOCKED" tinyint(1) [not null]
  "LOCKGRANTED" datetime [default: NULL]
  "LOCKEDBY" varchar(255) [default: NULL]
}

Table "address" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "address" varchar(255) [not null]
  "address2" varchar(255) [default: NULL]
  "city" varchar(255) [default: NULL]
  "country" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "postal_code" varchar(255) [default: NULL]
  "state_or_province" varchar(255) [default: NULL]
  "description" varchar(4000) [default: NULL]
}

Table "attribute" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "allow_other" bit(1) [default: NULL]
  "active" bit(1) [default: NULL]
  "allow_multiple" bit(1) [default: NULL]
  "code" varchar(255) [default: NULL]
  "default_value" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "required" bit(1) [default: NULL]
  "exportable" bit(1) [default: `b'1'`]
  "unit_of_measure_class_id" char(38) [default: NULL]

Indexes {
  code [unique, name: "code"]
  unit_of_measure_class_id [name: "FKC7AA9C4013CE80"]
}
}

Table "attribute_entity_type_codes" {
  "attribute_id" char(38) [default: NULL]
  "entity_type_code" varchar(255) [default: NULL]

Indexes {
  attribute_id [name: "FK38EE09DA47B0D087"]
}
}

Table "attribute_options" {
  "attribute_id" char(38) [default: NULL]
  "options_string" varchar(255) [default: NULL]
  "options_idx" int(11) [default: NULL]
}

Table "budget_code" {
  "id" char(38) [pk, not null]
  "code" longtext [not null]
  "name" longtext
  "description" longtext
  "organization_id" char(38) [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  organization_id [name: "fk_budget_code_organization"]
  created_by_id [name: "fk_budget_code_created_by"]
  updated_by_id [name: "fk_budget_code_updated_by"]
}
}

Table "category" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "parent_category_id" char(38) [default: NULL]
  "sort_order" int(11) [default: NULL]
  "is_root" tinyint(4) [default: NULL]
  "gl_account_id" char(38) [default: NULL]

Indexes {
  parent_category_id [name: "FK302BCFE619A2EF8"]
  gl_account_id [name: "fk_category_gl_account"]
}
}

Table "click_stream" {
  "id" bigint(20) [pk, not null]
  "date_created" datetime [not null]
  "hostname" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "referrer" varchar(255) [default: NULL]
  "session_id" varchar(255) [not null]
}

Table "click_stream_request" {
  "id" bigint(20) [pk, not null]
  "click_stream_id" bigint(20) [not null]
  "date_created" datetime [not null]
  "port" int(11) [default: NULL]
  "protocol" varchar(8) [not null]
  "query" varchar(255) [default: NULL]
  "server" varchar(255) [not null]
  "uri" varchar(255) [not null]
  "person" varchar(255) [default: NULL]

Indexes {
  click_stream_id [name: "FKFD8E50671A43AB29"]
}
}

Table "comment" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "comment" text
  "date_created" datetime [not null]
  "date_read" datetime [default: NULL]
  "date_sent" datetime [default: NULL]
  "last_updated" datetime [not null]
  "recipient_id" char(38) [default: NULL]
  "sender_id" char(38) [default: NULL]

Indexes {
  recipient_id [name: "FK38A5EE5FF885F087"]
  sender_id [name: "FK38A5EE5FAF1302EB"]
}
}

Table "consumption" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "day" int(11) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "month" int(11) [default: NULL]
  "product_id" char(38) [default: NULL]
  "year" int(11) [default: NULL]
  "location_id" char(38) [default: NULL]
  "transaction_date" datetime [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "quantity" int(11) [default: NULL]

Indexes {
  inventory_item_id [name: "FKCD71F39BAA992CED"]
  location_id [name: "FKCD71F39B8ABEBD5"]
  product_id [name: "FKCD71F39BDED5FAE7"]
}
}

Table "consumption_fact" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "location_key_id" bigint(20) [not null]
  "lot_key_id" bigint(20) [not null]
  "product_key_id" bigint(20) [not null]
  "quantity" decimal(19,2) [not null]
  "transaction_code" varchar(255) [not null]
  "transaction_date_key_id" bigint(20) [not null]
  "transaction_number" varchar(255) [not null]
  "transaction_type" varchar(255) [not null]
  "unit_cost" decimal(19,2) [not null]
  "unit_price" decimal(19,2) [not null]

Indexes {
  location_key_id [name: "FKA8B7A490A27827C2"]
  lot_key_id [name: "FKA8B7A490D1F27172"]
  product_key_id [name: "FKA8B7A49072882836"]
  transaction_date_key_id [name: "FKA8B7A490CA32CFEF"]
}
}

Table "container" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "container_number" varchar(255) [default: NULL]
  "container_type_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "height" float(12,3) [default: NULL]
  "last_updated" datetime [not null]
  "length" float(12,3) [default: NULL]
  "name" varchar(255) [default: NULL]
  "parent_container_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "shipment_id" char(38) [default: NULL]
  "volume_units" varchar(255) [default: NULL]
  "weight" float(12,3) [default: NULL]
  "weight_units" varchar(255) [default: NULL]
  "width" float(12,3) [default: NULL]
  "container_status" varchar(255) [default: NULL]
  "sort_order" int(11) [default: NULL]

Indexes {
  container_type_id [name: "FKE7814C8117A6E251"]
  parent_container_id [name: "FKE7814C814B6A2E03"]
  recipient_id [name: "FKE7814C8144979D51"]
  shipment_id [name: "FKE7814C813B5F6286"]
}
}

Table "container_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
}

Table "date_dimension" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "date" datetime [not null]
  "day_of_month" int(11) [not null]
  "day_of_week" int(11) [not null]
  "month" int(11) [not null]
  "month_name" varchar(255) [not null]
  "month_year" varchar(255) [not null]
  "week" int(11) [not null]
  "weekday_name" varchar(255) [not null]
  "year" int(11) [not null]

Indexes {
  date [unique, name: "date_dimension_date_idx"]
}
}

Table "document" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "content_type" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "document_number" varchar(255) [default: NULL]
  "document_type_id" char(38) [default: NULL]
  "extension" varchar(255) [default: NULL]
  "file_contents" mediumblob
  "file_uri" longtext
  "filename" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [default: NULL]

Indexes {
  document_type_id [name: "FK335CD11B6631D8CC"]
}
}

Table "document_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
  "document_code" varchar(255) [default: NULL]
}

Table "donor" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [default: NULL]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [default: NULL]
  "name" varchar(255) [not null]
}

Table "event" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "event_date" datetime [default: NULL]
  "event_location_id" char(38) [default: NULL]
  "event_type_id" char(38) [default: NULL]
  "last_updated" datetime [not null]

Indexes {
  event_location_id [name: "FK5C6729A4415A5B0"]
  event_type_id [name: "FK5C6729A3D970DB4"]
}
}

Table "event_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "event_code" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
}

Table "fulfillment" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "date_fulfilled" datetime [default: NULL]
  "fulfilled_by_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "status" varchar(255) [default: NULL]

Indexes {
  fulfilled_by_id [name: "FK5A2551DEAC392B33"]
}
}

Table "fulfillment_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "fulfillment_id" char(38) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "quantity" int(11) [default: NULL]
  "requisition_item_id" char(38) [default: NULL]

Indexes {
  fulfillment_id [name: "FKEDC55CD494567276"]
  inventory_item_id [name: "FKEDC55CD4AA992CED"]
  requisition_item_id [name: "FKEDC55CD447EBE106"]
}
}

Table "fulfillment_item_shipment_item" {
  "fulfillment_item_shipment_items_id" char(38) [default: NULL]
  "shipment_item_id" char(38) [default: NULL]

Indexes {
  fulfillment_item_shipment_items_id [name: "FKE071DE6DB42751E1"]
  shipment_item_id [name: "FKE071DE6DB06EC4FB"]
}
}

Table "gl_account" {
  "id" char(38) [pk, not null]
  "code" longtext [not null]
  "name" longtext
  "description" longtext
  "gl_account_type_id" char(38) [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  gl_account_type_id [name: "fk_gl_account_gl_account_type"]
  created_by_id [name: "fk_gl_account_created_by"]
  updated_by_id [name: "fk_gl_account_updated_by"]
}
}

Table "gl_account_type" {
  "id" char(38) [pk, not null]
  "code" longtext [not null]
  "name" longtext
  "gl_account_type_code" varchar(100) [default: "ASSET"]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  created_by_id [name: "fk_gl_account_type_created_by"]
  updated_by_id [name: "fk_gl_account_type_updated_by"]
}
}

Table "indicator" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "name" varchar(255) [not null]
  "description" varchar(2000) [not null]
  "expression" text [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
}

Table "inventory" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "last_inventory_date" datetime [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
}

Table "inventory_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "lot_number" varchar(255) [default: NULL]
  "product_id" char(38) [default: NULL]
  "expiration_date" datetime [default: NULL]
  "comments" varchar(255) [default: NULL]

Indexes {
  (product_id, lot_number) [unique, name: "product_id"]
}
}

Table "inventory_level" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "inventory_id" char(38) [default: NULL]
  "min_quantity" int(11) [default: NULL]
  "product_id" char(38) [default: NULL]
  "reorder_quantity" int(11) [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "status" varchar(255) [default: NULL]
  "max_quantity" int(11) [default: NULL]
  "bin_location" varchar(255) [default: NULL]
  "abc_class" varchar(255) [default: NULL]
  "preferred" tinyint(4) [default: NULL]
  "expected_lead_time_days" decimal(19,2) [default: NULL]
  "forecast_period_days" decimal(19,2) [default: NULL]
  "forecast_quantity" decimal(19,2) [default: NULL]
  "preferred_bin_location_id" char(38) [default: NULL]
  "replenishment_location_id" char(38) [default: NULL]
  "comments" varchar(255) [default: NULL]

Indexes {
  inventory_id [name: "FKC254A2E172A2C5B4"]
  product_id [name: "FKC254A2E1DED5FAE7"]
  preferred_bin_location_id [name: "FKC254A2E1CFDCB4DF"]
  replenishment_location_id [name: "FKC254A2E1F07D879A"]
}
}

Table "inventory_snapshot" {
  "id" char(38) [default: NULL]
  "version" int(11) [default: NULL]
  "product_id" char(38) [default: NULL]
  "location_id" char(38) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "quantity_on_hand" int(11) [default: NULL]
  "quantity_available_to_promise" int(11) [default: NULL]
  "quantity_inbound" int(11) [default: NULL]
  "quantity_outbound" int(11) [default: NULL]
  "last_updated" datetime [default: NULL]
  "date_created" datetime [default: NULL]
  "date" datetime [default: NULL]
  "bin_location_id" char(38) [default: NULL]
  "product_code" varchar(255) [not null]
  "lot_number" varchar(255) [default: "DEFAULT"]
  "expiration_date" datetime [default: NULL]
  "bin_location_name" varchar(255) [default: "DEFAULT"]

Indexes {
  (date, location_id, product_code, lot_number, bin_location_name) [unique, name: "inventory_snapshot_uniq_idx"]
  inventory_item_id [name: "FK740B547AA992CED"]
  product_id [name: "FK740B547DED5FAE7"]
  bin_location_id [name: "FK740B54769DB749D"]
  date [name: "inventory_snapshot_date_idx"]
  (location_id, last_updated) [name: "inventory_snapshot_last_updated_idx"]
}
}

Table "invoice" {
  "id" char(38) [pk, not null]
  "invoice_number" varchar(255) [not null]
  "name" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "invoice_type_id" char(38) [default: NULL]
  "party_from_id" char(38) [default: NULL]
  "party_id" char(38) [default: NULL]
  "date_invoiced" datetime [default: NULL]
  "date_submitted" datetime [default: NULL]
  "date_due" datetime [default: NULL]
  "date_paid" datetime [default: NULL]
  "currency_uom_id" char(38) [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "version" bigint(20) [not null]

Indexes {
  invoice_type_id [name: "fk_invoice_invoice_type"]
  party_from_id [name: "fk_invoice_party_from"]
  party_id [name: "fk_invoice_party"]
  currency_uom_id [name: "fk_invoice_currency_uom"]
  created_by_id [name: "fk_invoice_created_by"]
  updated_by_id [name: "fk_invoice_updated_by"]
}
}

Table "invoice_item" {
  "id" char(38) [pk, not null]
  "invoice_id" char(38) [not null]
  "product_id" char(38) [default: NULL]
  "gl_account_id" char(38) [default: NULL]
  "budget_code_id" char(38) [default: NULL]
  "quantity" decimal(19,2) [not null]
  "quantity_uom_id" char(38) [default: NULL]
  "quantity_per_uom" decimal(19,2) [not null]
  "amount" decimal(19,4) [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "version" bigint(20) [not null]

Indexes {
  invoice_id [name: "fk_invoice_item_invoice"]
  product_id [name: "fk_invoice_item_product"]
  gl_account_id [name: "fk_invoice_item_gl_account"]
  budget_code_id [name: "fk_invoice_item_budget_code"]
  quantity_uom_id [name: "fk_invoice_item_quantity_uom"]
  created_by_id [name: "fk_invoice_item_created_by"]
  updated_by_id [name: "fk_invoice_item_updated_by"]
}
}

Table "invoice_reference_number" {
  "invoice_reference_numbers_id" char(38) [default: NULL]
  "reference_number_id" char(38) [default: NULL]
  "reference_numbers_idx" int(11) [default: NULL]

Indexes {
  invoice_reference_numbers_id [name: "fk_invoice_reference_number_invoice_id"]
  reference_number_id [name: "fk_invoice_reference_number_reference_number_id"]
}
}

Table "invoice_type" {
  "id" char(38) [pk, not null]
  "name" varchar(255) [not null]
  "description" varchar(255) [default: NULL]
  "code" varchar(100) [default: "INVOICE"]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "version" bigint(20) [not null]

Indexes {
  created_by_id [name: "fk_invoice_type_created_by"]
  updated_by_id [name: "fk_invoice_type_updated_by"]
}
}

Table "local_transfer" {
  "id" char(38) [pk, not null, default: ""]
  "source_transaction_id" char(38) [default: NULL]
  "destination_transaction_id" char(38) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]

Indexes {
  destination_transaction_id [name: "FK7975323F4CC49445"]
  source_transaction_id [name: "FK7975323F57563498"]
}
}

Table "localization" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "code" varchar(250) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "locale" varchar(255) [not null]
  "text" varchar(2000) [not null]

Indexes {
  (code, locale) [unique, name: "localization_code_locale_idx"]
}
}

Table "location" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "address_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "logo_url" varchar(255) [default: NULL]
  "name" varchar(255) [not null]
  "inventory_id" char(38) [default: NULL]
  "manager_id" char(38) [default: NULL]
  "logo" mediumblob
  "managed_locally" bit(1) [default: NULL]
  "active" bit(1) [default: NULL]
  "location_type_id" char(38) [default: NULL]
  "parent_location_id" char(38) [default: NULL]
  "local" bit(1) [default: NULL]
  "bg_color" varchar(255) [default: NULL]
  "fg_color" varchar(255) [default: NULL]
  "location_group_id" char(38) [default: NULL]
  "sort_order" int(11) [default: "0"]
  "location_number" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "organization_id" varchar(255) [default: NULL]

Indexes {
  address_id [name: "FK714F9FB561ED379F"]
  inventory_id [name: "FK714F9FB572A2C5B4"]
  location_group_id [name: "FK714F9FB53BB36E94"]
  location_type_id [name: "FK714F9FB528F75F00"]
  manager_id [name: "FK714F9FB541E07A73"]
  parent_location_id [name: "FK714F9FB57AF9A3C0"]
  organization_id [name: "FK714F9FB5606C7D95"]
}
}

Table "location_dimension" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "location_group_name" varchar(255) [default: NULL]
  "location_id" varchar(255) [not null]
  "location_name" varchar(255) [not null]
  "location_number" varchar(255) [default: NULL]
  "location_type_code" varchar(255) [not null]
  "location_type_name" varchar(255) [not null]
  "parent_location_name" varchar(255) [default: NULL]

Indexes {
  location_id [name: "FK1143A95C8ABEBD5"]
}
}

Table "location_group" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "name" varchar(255) [default: NULL]
  "address_id" char(38) [default: NULL]

Indexes {
  address_id [name: "FK7A19D7561ED379F"]
}
}

Table "location_role" {
  "user_id" char(38) [default: NULL]
  "location_id" char(38) [default: NULL]
  "role_id" char(38) [default: NULL]
  "version" int(11) [default: NULL]
  "id" char(38) [default: NULL]
  "location_roles_idx" int(11) [default: NULL]

Indexes {
  location_id [name: "location_role_ibfk_3"]
  role_id [name: "location_role_ibfk_2"]
  user_id [name: "location_role_ibfk_1"]
}
}

Table "location_supported_activities" {
  "location_id" char(38) [default: NULL]
  "supported_activities_string" varchar(255) [default: NULL]

Indexes {
  location_id [name: "FKF58372688ABEBD5"]
}
}

Table "location_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
  "location_type_code" varchar(100) [default: NULL]
}

Table "location_type_supported_activities" {
  "location_type_id" char(38) [default: NULL]
  "supported_activities_string" varchar(255) [default: NULL]

Indexes {
  location_type_id [name: "FK7AFF67F928F75F00"]
}
}

Table "lot_dimension" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "expiration_date" datetime [default: NULL]
  "inventory_item_id" varchar(255) [not null]
  "lot_number" varchar(255) [default: NULL]
  "product_code" varchar(255) [not null]
}

Table "order" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [default: NULL]
  "date_ordered" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "destination_id" char(38) [default: NULL]
  "last_updated" datetime [default: NULL]
  "order_number" varchar(255) [default: NULL]
  "ordered_by_id" char(38) [default: NULL]
  "origin_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "status" varchar(255) [default: NULL]
  "completed_by_id" char(38) [default: NULL]
  "date_completed" datetime [default: NULL]
  "name" varchar(255) [not null]
  "order_type_code" varchar(100) [default: "PURCHASE_ORDER"]
  "currency_code" char(3) [default: NULL]
  "exchange_rate" decimal(19,8) [default: NULL]
  "payment_method_type_id" char(38) [default: NULL]
  "payment_term_id" char(38) [default: NULL]
  "approved_by_id" char(38) [default: NULL]
  "date_approved" datetime [default: NULL]
  "destination_party_id" char(38) [default: NULL]
  "origin_party_id" char(38) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  destination_id [name: "FK651874E1E2B3CDC"]
  ordered_by_id [name: "FK651874EAF6D8801"]
  origin_id [name: "FK651874EDBDEDAC4"]
  recipient_id [name: "FK651874E44979D51"]
  completed_by_id [name: "FK651874E41B7275F"]
  payment_method_type_id [name: "FK651874E6A8010C1"]
  payment_term_id [name: "FK651874E9E52B00C"]
  approved_by_id [name: "FK651874E240896CB"]
  destination_party_id [name: "FK651874E35D76CB0"]
  created_by_id [name: "FK651874E6D91063C"]
  updated_by_id [name: "FK651874E8E7F7DCF"]
}
}

Table "order_adjustment" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "order_id" char(38) [not null]
  "order_item_id" char(38) [default: NULL]
  "order_adjustment_type_id" char(38) [default: NULL]
  "amount" decimal(19,4) [default: NULL]
  "percentage" decimal(19,2) [default: NULL]
  "description" varchar(255) [default: NULL]
  "comments" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "budget_code_id" char(38) [default: NULL]
  "gl_account_id" char(38) [default: NULL]
  "canceled" bit(1) [default: NULL]

Indexes {
  order_adjustment_type_id [name: "FK4A1ABEFEE1A39520"]
  order_id [name: "FK4A1ABEFED08EDBE6"]
  order_item_id [name: "FK4A1ABEFE3BE9D843"]
  budget_code_id [name: "fk_order_adjustment_budget_code"]
  gl_account_id [name: "fk_order_adjustment_gl_account"]
}
}

Table "order_adjustment_invoice" {
  "invoice_item_id" char(38) [default: NULL]
  "order_adjustment_id" char(38) [default: NULL]

Indexes {
  order_adjustment_id [name: "order_adjustment_invoice_ibfk_1"]
  invoice_item_id [name: "order_adjustment_invoice_ibfk_2"]
}
}

Table "order_adjustment_type" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "name" varchar(255) [not null]
  "code" varchar(255) [not null]
  "description" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "gl_account_id" char(38) [default: NULL]

Indexes {
  gl_account_id [name: "fk_order_adjustment_type_gl_account"]
}
}

Table "order_comment" {
  "order_comments_id" char(38) [default: NULL]
  "comment_id" char(38) [default: NULL]

Indexes {
  comment_id [name: "FK2DE9EE6EC4A49BBF"]
  order_comments_id [name: "FK2DE9EE6EB8839C0F"]
}
}

Table "order_document" {
  "order_documents_id" char(38) [default: NULL]
  "document_id" char(38) [default: NULL]

Indexes {
  document_id [name: "FKE698D2ECC800AA15"]
  order_documents_id [name: "FKE698D2ECFE10118D"]
}
}

Table "order_event" {
  "order_events_id" char(38) [default: NULL]
  "event_id" char(38) [default: NULL]

Indexes {
  event_id [name: "FK74D92A69786431F"]
  order_events_id [name: "FK74D92A693D2E628A"]
}
}

Table "order_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "category_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "order_id" char(38) [default: NULL]
  "product_id" char(38) [default: NULL]
  "quantity" int(11) [not null]
  "requested_by_id" char(38) [default: NULL]
  "unit_price" decimal(19,4) [default: NULL]
  "order_item_status_code" varchar(100) [default: "PENDING"]
  "parent_order_item_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "destination_bin_location_id" char(38) [default: NULL]
  "origin_bin_location_id" char(38) [default: NULL]
  "currency_code" char(3) [default: NULL]
  "product_supplier_id" char(38) [default: NULL]
  "estimated_ready_date" datetime [default: NULL]
  "estimated_ship_date" datetime [default: NULL]
  "estimated_delivery_date" datetime [default: NULL]
  "actual_ready_date" datetime [default: NULL]
  "actual_ship_date" datetime [default: NULL]
  "actual_delivery_date" datetime [default: NULL]
  "product_package_id" char(38) [default: NULL]
  "quantity_per_uom" decimal(19,2) [default: NULL]
  "quantity_uom_id" char(38) [default: NULL]
  "budget_code_id" char(38) [default: NULL]
  "gl_account_id" char(38) [default: NULL]
  "order_index" int(11) [default: NULL]

Indexes {
  category_id [name: "FK2D110D64EF4C770D"]
  inventory_item_id [name: "FK2D110D64AA992CED"]
  order_id [name: "FK2D110D64D08EDBE6"]
  product_id [name: "FK2D110D64DED5FAE7"]
  requested_by_id [name: "FK2D110D64911E7578"]
  destination_bin_location_id [name: "FK2D110D64605326C"]
  origin_bin_location_id [name: "FK2D110D6418D76D84"]
  parent_order_item_id [name: "FK2D110D6451A9416E"]
  recipient_id [name: "FK2D110D6444979D51"]
  product_supplier_id [name: "FK2D110D6429542386"]
  product_package_id [name: "FK2D110D6429B2552E"]
  quantity_uom_id [name: "FK2D110D645ED93B03"]
  budget_code_id [name: "fk_order_item_budget_code"]
  gl_account_id [name: "fk_order_item_gl_account"]
}
}

Table "order_item_comment" {
  "order_item_comments_id" char(38) [default: NULL]
  "comment_id" char(38) [default: NULL]

Indexes {
  comment_id [name: "FKB5A4FE84C4A49BBF"]
}
}

Table "order_shipment" {
  "order_item_id" char(38) [default: NULL]
  "shipment_item_id" char(38) [default: NULL]

Indexes {
  order_item_id [name: "FK9475736B3BE9D843"]
  shipment_item_id [name: "FK9475736BB06EC4FB"]
}
}

Table "organization_sequences" {
  "sequences" varchar(255) [default: NULL]
  "sequences_idx" varchar(255) [default: NULL]
  "sequences_elt" varchar(255) [not null]
}

Table "party" {
  "id" varchar(255) [pk, not null]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "party_type_id" varchar(255) [not null]
  "class" varchar(255) [not null]
  "code" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "name" varchar(255) [default: NULL]
  "default_location_id" char(38) [default: NULL]

Indexes {
  party_type_id [name: "FK6581AE69DFE4C4C"]
  default_location_id [name: "FK6581AE6D1DFC6D7"]
}
}

Table "party_role" {
  "id" varchar(255) [pk, not null]
  "version" bigint(20) [not null]
  "end_date" datetime [default: NULL]
  "party_id" varchar(255) [not null]
  "role_type" varchar(255) [not null]
  "start_date" datetime [default: NULL]

Indexes {
  party_id [name: "FK1C92FE2F3E67CF9F"]
}
}

Table "party_type" {
  "id" varchar(255) [pk, not null]
  "version" bigint(20) [not null]
  "code" varchar(255) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "party_type_code" varchar(255) [not null]
}

Table "payment_method_type" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "name" varchar(255) [not null]
  "description" varchar(255) [default: NULL]
  "payment_method_type_code" varchar(255) [not null]
  "active" bit(1) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
}

Table "payment_term" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "name" varchar(255) [not null]
  "code" varchar(255) [not null]
  "description" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "prepayment_percent" decimal(19,2) [default: NULL]
  "days_to_payment" int(11) [default: NULL]
}

Table "person" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "email" varchar(255) [default: NULL]
  "first_name" varchar(255) [default: NULL]
  "last_name" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "phone_number" varchar(255) [default: NULL]
}

Table "picklist" {
  "id" char(38) [pk, not null]
  "name" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "picker_id" char(38) [default: NULL]
  "date_picked" datetime [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "requisition_id" char(38) [default: NULL]

Indexes {
  created_by_id [name: "FKD3F8383F217F5972"]
  picker_id [name: "FKD3F8383FA3E976BC"]
  updated_by_id [name: "FKD3F8383F426DD105"]
  requisition_id [name: "FKD3F8383F5DE9E374"]
}
}

Table "picklist_item" {
  "id" char(38) [pk, not null]
  "quantity" int(11) [default: NULL]
  "picklist_id" char(38) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "status" varchar(255) [default: NULL]
  "reason_code" varchar(255) [default: NULL]
  "comment" varchar(255) [default: NULL]
  "requisition_item_id" char(38) [default: NULL]
  "picklist_items_idx" int(11) [default: NULL]
  "bin_location_id" char(38) [default: NULL]
  "sort_order" int(11) [default: NULL]

Indexes {
  created_by_id [name: "picklist_item_ibfk_3"]
  inventory_item_id [name: "picklist_item_ibfk_5"]
  picklist_id [name: "picklist_item_ibfk_2"]
  requisition_item_id [name: "picklist_item_ibfk_1"]
  updated_by_id [name: "picklist_item_ibfk_4"]
  bin_location_id [name: "FKE7584B1369DB749D"]
}
}

Table "preference_type" {
  "id" char(38) [pk, not null]
  "name" varchar(255) [not null]
  "validation_code" varchar(100) [default: "DEFAULT"]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "version" bigint(20) [not null]

Indexes {
  name [unique, name: "name"]
  created_by_id [name: "fk_preference_type_created_by"]
  updated_by_id [name: "fk_preference_type_updated_by"]
}
}

Table "product" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "category_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "description" mediumtext
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "product_code" varchar(255) [default: NULL]
  "unit_of_measure_id" char(38) [default: NULL]
  "cold_chain" bit(1) [default: NULL]
  "manufacturer" varchar(255) [default: NULL]
  "manufacturer_code" varchar(255) [default: NULL]
  "ndc" varchar(255) [default: NULL]
  "upc" varchar(255) [default: NULL]
  "unit_of_measure" varchar(255) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "default_uom_id" char(38) [default: NULL]
  "brand_name" varchar(255) [default: NULL]
  "vendor" varchar(255) [default: NULL]
  "vendor_code" varchar(255) [default: NULL]
  "package_size" int(11) [default: NULL]
  "model_number" varchar(255) [default: NULL]
  "manufacturer_name" varchar(255) [default: NULL]
  "vendor_name" varchar(255) [default: NULL]
  "active" bit(1) [default: NULL]
  "controlled_substance" bit(1) [default: NULL]
  "essential" bit(1) [default: NULL]
  "hazardous_material" bit(1) [default: NULL]
  "lot_control" bit(1) [default: NULL]
  "serialized" bit(1) [default: NULL]
  "price_per_unit" decimal(19,4) [default: NULL]
  "reconditioned" bit(1) [default: NULL]
  "product_type_id" char(38) [default: NULL]
  "abc_class" varchar(255) [default: NULL]
  "cost_per_unit" decimal(19,4) [default: NULL]
  "gl_account_id" char(38) [default: NULL]

Indexes {
  product_code [unique, name: "product_code"]
  category_id [name: "FKED8DCCEFEF4C770D"]
  created_by_id [name: "FKED8DCCEF217F5972"]
  default_uom_id [name: "FKED8DCCEFEEB2908D"]
  updated_by_id [name: "FKED8DCCEF426DD105"]
  product_type_id [name: "FKED8DCCEFABD88AC6"]
  gl_account_id [name: "fk_product_gl_account"]
}
}

Table "product_association" {
  "id" char(38) [pk, not null]
  "code" varchar(100) [not null]
  "product_id" char(38) [not null]
  "associated_product_id" char(38) [not null]
  "quantity" decimal(19,2) [not null]
  "comments" varchar(255) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]

Indexes {
  associated_product_id [name: "FKED441931C8653BC0"]
  product_id [name: "FKED441931DED5FAE7"]
}
}

Table "product_attribute" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "attribute_id" char(38) [default: NULL]
  "product_id" char(38) [default: NULL]
  "attributes_idx" int(11) [default: NULL]
  "value" varchar(255) [default: NULL]
  "unit_of_measure_id" char(38) [default: NULL]
  "product_supplier_id" char(38) [default: NULL]

Indexes {
  attribute_id [name: "FK94A534C47B0D087"]
  product_id [name: "FK94A534CDED5FAE7"]
  unit_of_measure_id [name: "FK94A534C24DEBC91"]
  product_supplier_id [name: "FK94A534C29542386"]
}
}

Table "product_availability" {
  "id" char(38) [pk, not null]
  "version" int(11) [not null]
  "bin_location_id" char(38) [default: NULL]
  "inventory_item_id" char(38) [not null]
  "location_id" char(38) [not null]
  "product_id" char(38) [not null]
  "product_code" varchar(100) [not null]
  "lot_number" varchar(100) [not null, default: "DEFAULT"]
  "bin_location_name" varchar(100) [not null, default: "DEFAULT"]
  "quantity_allocated" int(11) [default: NULL]
  "quantity_on_hand" int(11) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]

Indexes {
  (location_id, product_code, lot_number, bin_location_name) [unique, name: "product_availability_uniq_idx"]
  bin_location_id [name: "FKD3FC6EAB69DB749D"]
  inventory_item_id [name: "FKD3FC6EABAA992CED"]
  product_id [name: "FKD3FC6EABDED5FAE7"]
}
}

Table "product_catalog" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "active" bit(1) [default: NULL]
  "code" varchar(255) [not null]
  "date_created" datetime [not null]
  "description" longtext
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "color" varchar(255) [default: NULL]

Indexes {
  code [unique, name: "code_idx"]
}
}

Table "product_catalog_item" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "active" bit(1) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "product_id" char(38) [not null]
  "product_catalog_id" char(38) [not null]

Indexes {
  product_catalog_id [name: "FK187E54C9FB5E604E"]
  product_id [name: "FK187E54C9DED5FAE7"]
}
}

Table "product_category" {
  "product_id" char(38) [default: NULL]
  "category_id" char(38) [default: NULL]
  "categories_idx" int(11) [default: NULL]

Indexes {
  product_id [name: "FKA0303E4EDED5FAE7"]
  category_id [name: "FKA0303E4EEF4C770D"]
}
}

Table "product_component" {
  "id" char(38) [pk, not null]
  "assembly_product_id" char(38) [not null]
  "component_product_id" char(38) [not null]
  "quantity" decimal(19,2) [not null]
  "unit_of_measure_id" char(38) [not null]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "product_components_idx" int(11) [default: NULL]

Indexes {
  component_product_id [name: "FKB511C5AD20E351EA"]
  unit_of_measure_id [name: "FKB511C5AD24DEBC91"]
  assembly_product_id [name: "FKB511C5ADFB4C199C"]
}
}

Table "product_demand_details" {
  "request_id" char(38) [not null, default: ""]
  "request_status" varchar(255) [default: NULL]
  "request_number" varchar(255) [default: NULL]
  "date_created" datetime [default: NULL]
  "date_requested" datetime [not null]
  "date_issued" datetime
  "origin_id" char(38) [not null, default: ""]
  "origin_name" varchar(255) [not null]
  "destination_id" char(38) [not null, default: ""]
  "destination_name" varchar(255) [not null]
  "request_item_id" char(38) [not null, default: ""]
  "product_id" char(38) [not null, default: ""]
  "product_code" varchar(255) [default: NULL]
  "product_name" varchar(255) [not null]
  "quantity_requested" int(11) [not null]
  "quantity_canceled" bigint(11) [not null, default: "0"]
  "quantity_approved" bigint(11) [not null, default: "0"]
  "quantity_modified" decimal(32,0) [not null, default: "0"]
  "quantity_picked" decimal(32,0) [not null, default: "0"]
  "quantity_demand" decimal(32,0) [not null, default: "0"]
  "reason_code" varchar(255) [default: NULL]
  "reason_code_classification" varchar(31) [default: NULL]

Indexes {
  (product_id, origin_id, destination_id, date_issued, date_requested) [name: "product_id"]
}
}

Table "product_demand_details_tmp" {
  "request_id" char(38) [not null, default: ""]
  "request_status" varchar(255) [default: NULL]
  "request_number" varchar(255) [default: NULL]
  "date_created" datetime [default: NULL]
  "date_requested" datetime [not null]
  "date_issued" datetime
  "origin_id" char(38) [not null, default: ""]
  "origin_name" varchar(255) [not null]
  "destination_id" char(38) [not null, default: ""]
  "destination_name" varchar(255) [not null]
  "request_item_id" char(38) [not null, default: ""]
  "product_id" char(38) [not null, default: ""]
  "product_code" varchar(255) [default: NULL]
  "product_name" varchar(255) [not null]
  "quantity_requested" int(11) [not null]
  "quantity_canceled" bigint(11) [not null, default: "0"]
  "quantity_approved" bigint(11) [not null, default: "0"]
  "quantity_modified" decimal(32,0) [not null, default: "0"]
  "quantity_picked" decimal(32,0) [not null, default: "0"]
  "quantity_demand" decimal(32,0) [not null, default: "0"]
  "reason_code" varchar(255) [default: NULL]
  "reason_code_classification" varchar(31) [default: NULL]
}

Table "product_dimension" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "abc_class" varchar(255) [default: NULL]
  "active" bit(1) [not null]
  "category_name" varchar(255) [not null]
  "generic_product" varchar(255) [default: NULL]
  "product_code" varchar(255) [not null]
  "product_id" varchar(255) [not null]
  "product_name" varchar(255) [not null]
  "unit_cost" decimal(19,2) [default: NULL]
  "unit_price" decimal(19,2) [default: NULL]

Indexes {
  product_id [name: "FKC73E1616DED5FAE7"]
}
}

Table "product_document" {
  "product_id" char(38) [default: NULL]
  "document_id" char(38) [default: NULL]

Indexes {
  document_id [name: "FKD08A526BC800AA15"]
  product_id [name: "FKD08A526BDED5FAE7"]
}
}

Table "product_group" {
  "id" char(38) [pk, not null]
  "name" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "category_id" char(38) [default: NULL]

Indexes {
  category_id [name: "FK51F3772FEF4C770D"]
}
}

Table "product_group_product" {
  "product_group_id" char(38) [default: NULL]
  "product_id" char(38) [default: NULL]
  "products_idx" int(11) [default: NULL]

Indexes {
  product_group_id [name: "FK313A4BDF14F7BB8E"]
  product_id [name: "FK313A4BDFDED5FAE7"]
}
}

Table "product_package" {
  "id" char(38) [pk, not null]
  "name" varchar(255) [default: NULL]
  "gtin" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "uom_id" char(38) [default: NULL]
  "product_id" char(38) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "quantity" int(11) [not null]
  "product_supplier_id" char(38) [default: NULL]
  "product_price_id" char(38) [default: NULL]

Indexes {
  (product_id, product_supplier_id, uom_id, quantity) [unique, name: "product_package_uniq_idx"]
  created_by_id [name: "FK615A48F6217F5972"]
  uom_id [name: "FK615A48F63906C4CF"]
  updated_by_id [name: "FK615A48F6426DD105"]
  product_supplier_id [name: "FK615A48F629542386"]
}
}

Table "product_price" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "type" varchar(255) [not null]
  "price" decimal(19,4) [not null]
  "currency_id" char(38) [default: NULL]
  "from_date" datetime [default: NULL]
  "to_date" datetime [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  currency_id [name: "fk_product_price_unit_of_measure"]
  created_by_id [name: "fk_product_price_created_by"]
  updated_by_id [name: "fk_product_price_updated_by"]
}
}

Table "product_supplier" {
  "id" varchar(255) [pk, not null]
  "version" bigint(20) [not null]
  "brand_name" varchar(255) [default: NULL]
  "code" varchar(255) [default: NULL]
  "comments" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "description" longtext
  "last_updated" datetime [not null]
  "manufacturer_id" varchar(255) [default: NULL]
  "manufacturer_code" varchar(255) [default: NULL]
  "manufacturer_name" varchar(255) [default: NULL]
  "min_order_quantity" decimal(19,2) [default: NULL]
  "model_number" varchar(255) [default: NULL]
  "name" varchar(255) [not null]
  "ndc" varchar(255) [default: NULL]
  "product_id" varchar(255) [not null]
  "product_code" varchar(255) [default: NULL]
  "rating_type_code" varchar(255) [default: NULL]
  "standard_lead_time_days" decimal(19,2) [default: NULL]
  "supplier_id" varchar(255) [default: NULL]
  "supplier_code" varchar(255) [default: NULL]
  "supplier_name" varchar(255) [default: NULL]
  "unit_of_measure_id" varchar(255) [default: NULL]
  "unit_price" decimal(19,4) [default: NULL]
  "upc" varchar(255) [default: NULL]
  "unit_cost" decimal(19,4) [default: NULL]
  "contract_price_id" char(38) [default: NULL]

Indexes {
  manufacturer_id [name: "FK3A097B1C2A475A37"]
  product_id [name: "FK3A097B1CDED5FAE7"]
  supplier_id [name: "FK3A097B1CF42F7E5C"]
  unit_of_measure_id [name: "FK3A097B1C24DEBC91"]
}
}

Table "product_supplier_preference" {
  "id" char(38) [pk, not null]
  "product_supplier_id" char(38) [default: NULL]
  "destination_party_id" char(38) [default: NULL]
  "preference_type_id" char(38) [default: NULL]
  "comments" varchar(255) [default: NULL]
  "validity_start_date" datetime [default: NULL]
  "validity_end_date" datetime [default: NULL]
  "date_created" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "version" bigint(20) [not null]

Indexes {
  product_supplier_id [name: "fk_product_supplier_preference_product_supplier"]
  destination_party_id [name: "fk_product_supplier_preference_destination_party"]
  preference_type_id [name: "fk_product_supplier_preference_preference_type"]
  created_by_id [name: "fk_product_supplier_preference_created_by"]
  updated_by_id [name: "fk_product_supplier_preference_updated_by"]
}
}

Table "product_tag" {
  "product_id" varchar(255) [not null]
  "tag_id" varchar(255) [default: NULL]

Indexes {
  product_id [name: "FKA71CAC4ADED5FAE7"]
  tag_id [name: "FKA71CAC4A9740C85F"]
}
}

Table "product_type" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "product_type_code" varchar(255) [not null]
  "product_identifier_format" varchar(255) [default: NULL]
  "code" varchar(255) [default: NULL]
  "sequence_number" int(11) [default: NULL]
}

Table "product_type_displayed_fields" {
  "product_type_id" char(38) [default: NULL]
  "product_field" varchar(255) [default: NULL]

Indexes {
  product_type_id [name: "fk_product_type_displayed_fields_product_type"]
}
}

Table "product_type_required_fields" {
  "product_type_id" char(38) [default: NULL]
  "product_field" varchar(255) [default: NULL]

Indexes {
  product_type_id [name: "fk_product_type_required_fields_product_type"]
}
}

Table "product_type_supported_activities" {
  "product_type_id" char(38) [default: NULL]
  "product_activity_code" varchar(255) [default: NULL]

Indexes {
  product_type_id [name: "fk_product_type_supported_activities_product_type"]
}
}

Table "receipt" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "actual_delivery_date" datetime [default: NULL]
  "date_created" datetime [not null]
  "expected_delivery_date" datetime [default: NULL]
  "last_updated" datetime [not null]
  "recipient_id" char(38) [default: NULL]
  "shipment_id" char(38) [default: NULL]
  "receipt_number" varchar(255) [default: NULL]
  "receipt_status_code" varchar(255) [default: NULL]

Indexes {
  recipient_id [name: "FK4082723844979D51"]
  shipment_id [name: "FK408272383B5F6286"]
}
}

Table "receipt_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "comment_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "expiration_date" datetime [default: NULL]
  "last_updated" datetime [not null]
  "lot_number" varchar(255) [default: NULL]
  "product_id" char(38) [default: NULL]
  "quantity_shipped" int(11) [default: NULL]
  "quantity_received" int(11) [default: NULL]
  "receipt_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "comment" varchar(255) [default: NULL]
  "shipment_item_id" char(38) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "bin_location_id" char(38) [default: NULL]
  "quantity_canceled" int(11) [default: NULL]
  "is_split_item" bit(1) [default: NULL]
  "sort_order" int(11) [default: NULL]

Indexes {
  product_id [name: "FKAE3064BADED5FAE7"]
  receipt_id [name: "FKAE3064BAF7076438"]
  recipient_id [name: "FKAE3064BA44979D51"]
  shipment_item_id [name: "FKAE3064BAB06EC4FB"]
  inventory_item_id [name: "FKAE3064BAAA992CED"]
  bin_location_id [name: "FKAE3064BA69DB749D"]
}
}

Table "reference_number" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "identifier" varchar(255) [default: NULL]
  "reference_number_type_id" char(38) [default: NULL]

Indexes {
  reference_number_type_id [name: "FKD790DEBD154F600"]
}
}

Table "reference_number_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
}

Table "requisition" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [default: NULL]
  "date_requested" datetime [not null]
  "description" varchar(255) [default: NULL]
  "destination_id" char(38) [default: NULL]
  "last_updated" datetime [default: NULL]
  "origin_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "request_number" varchar(255) [default: NULL]
  "requested_by_id" char(38) [default: NULL]
  "status" varchar(255) [default: NULL]
  "fulfillment_id" char(38) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "name" varchar(255) [default: NULL]
  "date_valid_from" datetime [default: NULL]
  "date_valid_to" datetime [default: NULL]
  "recipient_program" varchar(255) [default: NULL]
  "requested_delivery_date" datetime [not null]
  "type" varchar(255) [default: NULL]
  "commodity_class" varchar(255) [default: NULL]
  "is_template" tinyint(4) [default: NULL]
  "is_published" tinyint(4) [default: NULL]
  "date_published" datetime [default: NULL]
  "verified_by_id" char(38) [default: NULL]
  "date_verified" datetime [default: NULL]
  "reviewed_by_id" char(38) [default: NULL]
  "date_reviewed" datetime [default: NULL]
  "delivered_by_id" char(38) [default: NULL]
  "date_delivered" datetime [default: NULL]
  "received_by_id" char(38) [default: NULL]
  "date_received" datetime [default: NULL]
  "checked_by_id" char(38) [default: NULL]
  "date_checked" datetime [default: NULL]
  "issued_by_id" char(38) [default: NULL]
  "date_issued" datetime [default: NULL]
  "requisition_template_id" char(38) [default: NULL]
  "replenishment_period" int(11) [default: NULL]
  "sort_by_code" varchar(255) [default: NULL]
  "source_type" varchar(255) [default: NULL]

Indexes {
  destination_id [name: "FK414EF28F1E2B3CDC"]
  fulfillment_id [name: "FK414EF28F94567276"]
  origin_id [name: "FK414EF28FDBDEDAC4"]
  recipient_id [name: "FK414EF28F44979D51"]
  requested_by_id [name: "FK414EF28FDD302242"]
  checked_by_id [name: "FK1799509CD2CB8BBB"]
  created_by_id [name: "FK1799509C217F5972"]
  delivered_by_id [name: "FK1799509C4CF042D8"]
  issued_by_id [name: "FK1799509CD196DBBF"]
  received_by_id [name: "FK1799509C36C69275"]
  reviewed_by_id [name: "FK1799509CDFA74E0B"]
  updated_by_id [name: "FK1799509C426DD105"]
  verified_by_id [name: "FK1799509C20E33E1C"]
  requisition_template_id [name: "FK1799509C2BDD17B3"]
}
}

Table "requisition_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "category_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "product_id" char(38) [not null]
  "quantity" int(11) [not null]
  "requisition_id" char(38) [default: NULL]
  "requested_by_id" char(38) [default: NULL]
  "unit_price" float(12,0) [default: NULL]
  "product_group_id" char(38) [default: NULL]
  "comment" varchar(255) [default: NULL]
  "recipient_id" varchar(255) [default: NULL]
  "substitutable" bit(1) [not null]
  "order_index" int(11) [default: NULL]
  "requisition_items_idx" int(11) [default: NULL]
  "quantity_canceled" int(11) [default: NULL]
  "cancel_reason_code" varchar(255) [default: NULL]
  "cancel_comments" varchar(255) [default: NULL]
  "parent_requisition_item_id" char(38) [default: NULL]
  "product_package_id" char(38) [default: NULL]
  "requisition_item_type" varchar(255) [default: NULL]
  "quantity_approved" int(11) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "substitution_item_id" char(38) [default: NULL]
  "modification_item_id" char(38) [default: NULL]
  "pallet_name" varchar(255) [default: NULL]
  "box_name" varchar(255) [default: NULL]
  "lot_number" varchar(255) [default: NULL]
  "expiration_date" datetime [default: NULL]
  "pick_reason_code" varchar(255) [default: NULL]

Indexes {
  category_id [name: "FK4DA982C3EF4C770D"]
  inventory_item_id [name: "FK4DA982C3AA992CED"]
  product_id [name: "FK4DA982C3DED5FAE7"]
  requisition_id [name: "FK4DA982C35DE21C87"]
  created_by_id [name: "FK5358E4D6217F5972"]
  product_group_id [name: "FK5358E4D614F7BB8E"]
  requested_by_id [name: "FK5358E4D6DD302242"]
  updated_by_id [name: "FK5358E4D6426DD105"]
  product_package_id [name: "FK5358E4D629B2552E"]
  modification_item_id [name: "FK5358E4D6405AC22D"]
  parent_requisition_item_id [name: "FK5358E4D6F84BDE18"]
  substitution_item_id [name: "FK5358E4D61594028E"]
  recipient_id [name: "FK5358E4D644979D51"]
}
}

Table "role" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "description" varchar(255) [default: NULL]
  "role_type" varchar(255) [not null]
  "name" varchar(255) [default: NULL]
}

Table "shipment" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "carrier_id" char(38) [default: NULL]
  "date_created" datetime [default: NULL]
  "destination_id" char(38) [default: NULL]
  "donor_id" char(38) [default: NULL]
  "expected_delivery_date" datetime [default: NULL]
  "expected_shipping_date" datetime [default: NULL]
  "last_updated" datetime [default: NULL]
  "name" varchar(255) [not null]
  "origin_id" char(38) [default: NULL]
  "recipient_id" char(38) [default: NULL]
  "shipment_method_id" char(38) [default: NULL]
  "shipment_number" varchar(255) [default: NULL]
  "shipment_type_id" char(38) [default: NULL]
  "total_value" float(12,2) [default: NULL]
  "additional_information" longtext
  "stated_value" float(12,2) [default: NULL]
  "weight" float(12,0) [default: NULL]
  "weight_units" varchar(255) [default: NULL]
  "current_status" varchar(255) [default: NULL]
  "current_event_id" char(38) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "requisition_id" char(38) [default: NULL]
  "description" text
  "driver_name" varchar(255) [default: NULL]

Indexes {
  carrier_id [name: "FKE139719A294C1012"]
  destination_id [name: "FKE139719A1E2B3CDC"]
  donor_id [name: "FKE139719A49AB6B52"]
  origin_id [name: "FKE139719ADBDEDAC4"]
  recipient_id [name: "FKE139719A44979D51"]
  shipment_method_id [name: "FKE139719AA28CC5FB"]
  shipment_type_id [name: "FKE139719AFF77FF9B"]
  current_event_id [name: "FKE139719AD95ACF25"]
  created_by_id [name: "FKE139719A217F5972"]
  updated_by_id [name: "FKE139719A426DD105"]
  requisition_id [name: "FKE139719A5DE9E374"]
}
}

Table "shipment_comment" {
  "shipment_comments_id" char(38) [default: NULL]
  "comment_id" char(38) [default: NULL]
  "comments_idx" int(11) [default: NULL]

Indexes {
  comment_id [name: "FKC398CCBAC4A49BBF"]
}
}

Table "shipment_document" {
  "shipment_documents_id" char(38) [default: NULL]
  "document_id" char(38) [default: NULL]
  "documents_idx" int(11) [default: NULL]

Indexes {
  document_id [name: "FK6C5BE20C800AA15"]
}
}

Table "shipment_event" {
  "shipment_events_id" char(38) [default: NULL]
  "event_id" char(38) [default: NULL]

Indexes {
  event_id [name: "FK6D032BB5786431F"]
  shipment_events_id [name: "FK6D032BB53B350242"]
}
}

Table "shipment_invoice" {
  "invoice_item_id" char(38) [default: NULL]
  "shipment_item_id" char(38) [default: NULL]

Indexes {
  shipment_item_id [name: "shipment_invoice_ibfk_1"]
  invoice_item_id [name: "shipment_invoice_ibfk_2"]
}
}

Table "shipment_item" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "container_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "donor_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "lot_number" varchar(255) [default: NULL]
  "product_id" char(38) [default: NULL]
  "quantity" int(11) [not null]
  "recipient_id" char(38) [default: NULL]
  "shipment_items_idx" int(11) [default: NULL]
  "shipment_id" char(38) [default: NULL]
  "expiration_date" datetime [default: NULL]
  "inventory_item_id" char(38) [default: NULL]
  "bin_location_id" char(38) [default: NULL]
  "requisition_item_id" char(38) [default: NULL]
  "sort_order" int(11) [default: NULL]

Indexes {
  container_id [name: "FKDA3BB2987400E88E"]
  donor_id [name: "FKDA3BB29849AB6B52"]
  product_id [name: "FKDA3BB298DED5FAE7"]
  recipient_id [name: "FKDA3BB29844979D51"]
  shipment_id [name: "FKDA3BB2983B5F6286"]
  inventory_item_id [name: "FKDA3BB298AA992CED"]
  bin_location_id [name: "FKDA3BB29869DB749D"]
  requisition_item_id [name: "FKDA3BB2981CD3412D"]
}
}

Table "shipment_method" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "shipper_service_id" char(38) [default: NULL]
  "tracking_number" varchar(255) [default: NULL]
  "shipper_id" char(38) [default: NULL]

Indexes {
  shipper_id [name: "FK40203B263896C98E"]
  shipper_service_id [name: "FK40203B26296B2CA3"]
}
}

Table "shipment_reference_number" {
  "shipment_reference_numbers_id" char(38) [default: NULL]
  "reference_number_id" char(38) [default: NULL]
  "reference_numbers_idx" int(11) [default: NULL]

Indexes {
  reference_number_id [name: "FK312F6C292388BC5"]
}
}

Table "shipment_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
}

Table "shipment_workflow" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "shipment_type_id" char(38) [default: NULL]
  "excluded_fields" varchar(255) [default: NULL]
  "document_template" varchar(255) [default: NULL]

Indexes {
  shipment_type_id [name: "FKD584C4C4FF77FF9B"]
}
}

Table "shipment_workflow_container_type" {
  "shipment_workflow_container_types_id" char(38) [default: NULL]
  "container_type_id" char(38) [default: NULL]
  "container_types_idx" int(11) [default: NULL]

Indexes {
  container_type_id [name: "FKDEF5AD1317A6E251"]
}
}

Table "shipment_workflow_document" {
  "shipment_workflow_id" char(38) [not null]
  "document_id" char(38) [default: NULL]

Indexes {
  document_id [name: "FK9A945A36C800AA15"]
  shipment_workflow_id [name: "FK9A945A36EC587CFB"]
}
}

Table "shipment_workflow_document_template" {
  "shipment_workflow_id" char(38) [default: NULL]
  "document_id" char(38) [default: NULL]
}

Table "shipment_workflow_reference_number_type" {
  "shipment_workflow_reference_number_types_id" char(38) [default: NULL]
  "reference_number_type_id" char(38) [default: NULL]
  "reference_number_types_idx" int(11) [default: NULL]

Indexes {
  reference_number_type_id [name: "FK4BB27241154F600"]
}
}

Table "shipper" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [default: NULL]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [default: NULL]
  "name" varchar(255) [not null]
  "parameter_name" varchar(255) [default: NULL]
  "tracking_format" varchar(255) [default: NULL]
  "tracking_url" varchar(255) [default: NULL]
}

Table "shipper_service" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "description" varchar(255) [default: NULL]
  "name" varchar(255) [default: NULL]
  "shipper_id" char(38) [default: NULL]

Indexes {
  shipper_id [name: "FKDF7559D73896C98E"]
}
}

Table "stockout_fact" {
  "date_dimension_id" bigint(20) [not null]
  "location_dimension_id" bigint(20) [not null]
  "product_dimension_id" bigint(20) [not null]
  "quantity_on_hand" smallint(6) [default: NULL]

Indexes {
  (date_dimension_id, location_dimension_id, product_dimension_id) [pk]
}
}

Table "synonym" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "name" varchar(255) [not null]
  "product_id" char(38) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "locale" varchar(50) [default: NULL]

Indexes {
  created_by_id [name: "FK98293BFB217F5972"]
  updated_by_id [name: "FK98293BFB426DD105"]
  product_id [name: "FK299E50ABDED5FAE7"]
}
}

Table "tag" {
  "id" varchar(255) [pk, not null]
  "version" bigint(20) [not null]
  "created_by_id" varchar(255) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "tag" varchar(255) [not null]
  "updated_by_id" varchar(255) [default: NULL]
  "is_active" tinyint(4) [default: NULL]

Indexes {
  created_by_id [name: "FK1BF9A217F5972"]
  updated_by_id [name: "FK1BF9A426DD105"]
}
}

Table "transaction" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "created_by_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "destination_id" char(38) [default: NULL]
  "inventory_id" char(38) [default: NULL]
  "last_updated" datetime [not null]
  "source_id" char(38) [default: NULL]
  "transaction_date" datetime [not null]
  "transaction_type_id" char(38) [default: NULL]
  "confirmed" bit(1) [default: NULL]
  "confirmed_by_id" char(38) [default: NULL]
  "date_confirmed" datetime [default: NULL]
  "comment" varchar(255) [default: NULL]
  "incoming_shipment_id" char(38) [default: NULL]
  "outgoing_shipment_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]
  "transaction_number" varchar(255) [default: NULL]
  "requisition_id" char(38) [default: NULL]
  "order_id" char(38) [default: NULL]
  "receipt_id" char(38) [default: NULL]

Indexes {
  confirmed_by_id [name: "FK7FA0D2DE3265A8A9"]
  created_by_id [name: "FK7FA0D2DE217F5972"]
  destination_id [name: "FK7FA0D2DE1E2B3CDC"]
  inventory_id [name: "FK7FA0D2DE72A2C5B4"]
  source_id [name: "FK7FA0D2DE828481AF"]
  transaction_type_id [name: "FK7FA0D2DEB3FB7111"]
  updated_by_id [name: "FK7FA0D2DE426DD105"]
  requisition_id [name: "FK7FA0D2DE5DE9E374"]
  incoming_shipment_id [name: "FK7FA0D2DE5F12AFED"]
  outgoing_shipment_id [name: "FK7FA0D2DEB80B3233"]
  order_id [name: "FK7FA0D2DED08EDBE6"]
  receipt_id [name: "FK7FA0D2DEF7076438"]
}
}

Table "transaction_entry" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "inventory_item_id" char(38) [default: NULL]
  "quantity" int(11) [not null]
  "transaction_id" char(38) [default: NULL]
  "comments" varchar(255) [default: NULL]
  "transaction_entries_idx" int(11) [default: NULL]
  "bin_location_id" char(38) [default: NULL]
  "product_id" char(38) [default: NULL]
  "reason_code" varchar(255) [default: NULL]

Indexes {
  inventory_item_id [name: "FKABC21FD1AA992CED"]
  transaction_id [name: "FKABC21FD12EF4C7F4"]
  bin_location_id [name: "FKABC21FD169DB749D"]
  product_id [name: "FKABC21FD1DED5FAE7"]
}
}

Table "transaction_fact" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "location_key_id" bigint(20) [not null]
  "lot_key_id" bigint(20) [not null]
  "product_key_id" bigint(20) [not null]
  "quantity" decimal(19,2) [default: NULL]
  "transaction_date" datetime [not null]
  "transaction_date_key_id" bigint(20) [not null]
  "transaction_number" varchar(255) [not null]
  "transaction_type_key_id" bigint(20) [not null]

Indexes {
  location_key_id [name: "FK1E50D72DA27827C2"]
  lot_key_id [name: "FK1E50D72DD1F27172"]
  product_key_id [name: "FK1E50D72D72882836"]
  transaction_date_key_id [name: "FK1E50D72DCA32CFEF"]
  transaction_type_key_id [name: "FK1E50D72DCA354381"]
}
}

Table "transaction_type" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "description" varchar(255) [default: NULL]
  "last_updated" datetime [not null]
  "name" varchar(255) [not null]
  "sort_order" int(11) [default: NULL]
  "transaction_code" varchar(255) [not null]
}

Table "transaction_type_dimension" {
  "id" bigint(20) [pk, not null, increment]
  "version" bigint(20) [not null]
  "transaction_code" varchar(255) [not null]
  "transaction_type_id" varchar(255) [not null]
  "transaction_type_name" varchar(255) [not null]
}

Table "unit_of_measure" {
  "id" char(38) [pk, not null, default: ""]
  "version" bigint(20) [not null]
  "code" varchar(255) [not null]
  "description" varchar(255) [default: NULL]
  "name" varchar(255) [not null]
  "uom_class_id" char(38) [default: NULL]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  created_by_id [name: "FK7348B491217F5972"]
  updated_by_id [name: "FK7348B491426DD105"]
  uom_class_id [name: "FK7348B49197D8303E"]
}
}

Table "unit_of_measure_class" {
  "id" char(38) [pk, not null]
  "active" bit(1) [default: `b'1'`]
  "name" varchar(255) [default: NULL]
  "code" varchar(255) [default: NULL]
  "description" varchar(255) [default: NULL]
  "base_uom_id" char(38) [default: NULL]
  "version" bigint(20) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]
  "type" varchar(255) [default: NULL]
  "created_by_id" char(38) [default: NULL]
  "updated_by_id" char(38) [default: NULL]

Indexes {
  base_uom_id [name: "FK5D1B504A6B9DFD"]
  created_by_id [name: "FK5D1B504A217F5972"]
  updated_by_id [name: "FK5D1B504A426DD105"]
}
}

Table "unit_of_measure_conversion" {
  "id" char(38) [pk, not null]
  "version" bigint(20) [not null]
  "active" bit(1) [not null]
  "from_unit_of_measure_id" char(38) [not null]
  "to_unit_of_measure_id" char(38) [not null]
  "conversion_rate" decimal(19,8) [not null]
  "date_created" datetime [not null]
  "last_updated" datetime [not null]

Indexes {
  from_unit_of_measure_id [name: "FK2E4511844A3E746"]
  to_unit_of_measure_id [name: "FK2E4511849B9434D5"]
}
}

Table "user" {
  "id" char(38) [pk, not null, default: ""]
  "active" bit(1) [default: NULL]
  "last_login_date" datetime [default: NULL]
  "manager_id" char(38) [default: NULL]
  "password" varchar(255) [default: NULL]
  "username" varchar(255) [default: NULL]
  "warehouse_id" char(38) [default: NULL]
  "photo" mediumblob
  "locale" varchar(255) [default: NULL]
  "remember_last_location" bit(1) [default: NULL]
  "timezone" varchar(255) [default: NULL]
  "dashboard_config" longblob

Indexes {
  username [unique, name: "username"]
  manager_id [name: "FK36EBCB41E07A73"]
  warehouse_id [name: "FK36EBCB1F28CE07"]
}
}

Table "user_role" {
  "user_id" char(38) [default: NULL]
  "role_id" char(38) [default: NULL]

Indexes {
  role_id [name: "FK143BF46AFF37FDB5"]
  user_id [name: "FK143BF46AA462C195"]
}
}

Ref:"unit_of_measure_class"."id" < "attribute"."unit_of_measure_class_id"

Ref:"attribute"."id" < "attribute_entity_type_codes"."attribute_id"

Ref:"party"."id" < "budget_code"."organization_id"

Ref:"user"."id" < "budget_code"."created_by_id"

Ref:"user"."id" < "budget_code"."updated_by_id"

Ref:"category"."id" < "category"."parent_category_id"

Ref:"gl_account"."id" < "category"."gl_account_id"

Ref:"click_stream"."id" < "click_stream_request"."click_stream_id"

Ref:"user"."id" < "comment"."recipient_id"

Ref:"user"."id" < "comment"."sender_id"

Ref:"inventory_item"."id" < "consumption"."inventory_item_id"

Ref:"product"."id" < "consumption"."product_id"

Ref:"location"."id" < "consumption"."location_id"

Ref:"location_dimension"."id" < "consumption_fact"."location_key_id"

Ref:"lot_dimension"."id" < "consumption_fact"."lot_key_id"

Ref:"product_dimension"."id" < "consumption_fact"."product_key_id"

Ref:"date_dimension"."id" < "consumption_fact"."transaction_date_key_id"

Ref:"container_type"."id" < "container"."container_type_id"

Ref:"container"."id" < "container"."parent_container_id"

Ref:"person"."id" < "container"."recipient_id"

Ref:"shipment"."id" < "container"."shipment_id"

Ref:"document_type"."id" < "document"."document_type_id"

Ref:"location"."id" < "event"."event_location_id"

Ref:"event_type"."id" < "event"."event_type_id"

Ref:"person"."id" < "fulfillment"."fulfilled_by_id"

Ref:"fulfillment"."id" < "fulfillment_item"."fulfillment_id"

Ref:"inventory_item"."id" < "fulfillment_item"."inventory_item_id"

Ref:"requisition_item"."id" < "fulfillment_item"."requisition_item_id"

Ref:"fulfillment_item"."id" < "fulfillment_item_shipment_item"."fulfillment_item_shipment_items_id"

Ref:"shipment_item"."id" < "fulfillment_item_shipment_item"."shipment_item_id"

Ref:"gl_account_type"."id" < "gl_account"."gl_account_type_id"

Ref:"user"."id" < "gl_account"."created_by_id"

Ref:"user"."id" < "gl_account"."updated_by_id"

Ref:"user"."id" < "gl_account_type"."created_by_id"

Ref:"user"."id" < "gl_account_type"."updated_by_id"

Ref:"product"."id" < "inventory_item"."product_id"

Ref:"inventory"."id" < "inventory_level"."inventory_id"

Ref:"product"."id" < "inventory_level"."product_id"

Ref:"location"."id" < "inventory_level"."preferred_bin_location_id"

Ref:"location"."id" < "inventory_level"."replenishment_location_id"

Ref:"product"."id" < "inventory_snapshot"."product_id"

Ref:"location"."id" < "inventory_snapshot"."location_id"

Ref:"inventory_item"."id" < "inventory_snapshot"."inventory_item_id"

Ref:"location"."id" < "inventory_snapshot"."bin_location_id"

Ref:"invoice_type"."id" < "invoice"."invoice_type_id"

Ref:"party"."id" < "invoice"."party_from_id"

Ref:"party"."id" < "invoice"."party_id"

Ref:"unit_of_measure"."id" < "invoice"."currency_uom_id"

Ref:"user"."id" < "invoice"."created_by_id"

Ref:"user"."id" < "invoice"."updated_by_id"

Ref:"invoice"."id" < "invoice_item"."invoice_id"

Ref:"product"."id" < "invoice_item"."product_id"

Ref:"gl_account"."id" < "invoice_item"."gl_account_id"

Ref:"budget_code"."id" < "invoice_item"."budget_code_id"

Ref:"unit_of_measure"."id" < "invoice_item"."quantity_uom_id"

Ref:"user"."id" < "invoice_item"."created_by_id"

Ref:"user"."id" < "invoice_item"."updated_by_id"

Ref:"invoice"."id" < "invoice_reference_number"."invoice_reference_numbers_id"

Ref:"reference_number"."id" < "invoice_reference_number"."reference_number_id"

Ref:"user"."id" < "invoice_type"."created_by_id"

Ref:"user"."id" < "invoice_type"."updated_by_id"

Ref:"transaction"."id" < "local_transfer"."source_transaction_id"

Ref:"transaction"."id" < "local_transfer"."destination_transaction_id"

Ref:"address"."id" < "location"."address_id"

Ref:"inventory"."id" < "location"."inventory_id"

Ref:"user"."id" < "location"."manager_id"

Ref:"location_type"."id" < "location"."location_type_id"

Ref:"location"."id" < "location"."parent_location_id"

Ref:"location_group"."id" < "location"."location_group_id"

Ref:"party"."id" < "location"."organization_id"

Ref:"location"."id" < "location_dimension"."location_id"

Ref:"address"."id" < "location_group"."address_id"

Ref:"user"."id" < "location_role"."user_id"

Ref:"location"."id" < "location_role"."location_id"

Ref:"role"."id" < "location_role"."role_id"

Ref:"location"."id" < "location_supported_activities"."location_id"

Ref:"location_type"."id" < "location_type_supported_activities"."location_type_id"

Ref:"location"."id" < "order"."destination_id"

Ref:"person"."id" < "order"."ordered_by_id"

Ref:"location"."id" < "order"."origin_id"

Ref:"person"."id" < "order"."recipient_id"

Ref:"person"."id" < "order"."completed_by_id"

Ref:"payment_method_type"."id" < "order"."payment_method_type_id"

Ref:"payment_term"."id" < "order"."payment_term_id"

Ref:"person"."id" < "order"."approved_by_id"

Ref:"party"."id" < "order"."destination_party_id"

Ref:"person"."id" < "order"."created_by_id"

Ref:"person"."id" < "order"."updated_by_id"

Ref:"order"."id" < "order_adjustment"."order_id"

Ref:"order_item"."id" < "order_adjustment"."order_item_id"

Ref:"order_adjustment_type"."id" < "order_adjustment"."order_adjustment_type_id"

Ref:"budget_code"."id" < "order_adjustment"."budget_code_id"

Ref:"gl_account"."id" < "order_adjustment"."gl_account_id"

Ref:"invoice_item"."id" < "order_adjustment_invoice"."invoice_item_id"

Ref:"order_adjustment"."id" < "order_adjustment_invoice"."order_adjustment_id"

Ref:"gl_account"."id" < "order_adjustment_type"."gl_account_id"

Ref:"order"."id" < "order_comment"."order_comments_id"

Ref:"comment"."id" < "order_comment"."comment_id"

Ref:"order"."id" < "order_document"."order_documents_id"

Ref:"document"."id" < "order_document"."document_id"

Ref:"order"."id" < "order_event"."order_events_id"

Ref:"event"."id" < "order_event"."event_id"

Ref:"category"."id" < "order_item"."category_id"

Ref:"inventory_item"."id" < "order_item"."inventory_item_id"

Ref:"order"."id" < "order_item"."order_id"

Ref:"product"."id" < "order_item"."product_id"

Ref:"user"."id" < "order_item"."requested_by_id"

Ref:"order_item"."id" < "order_item"."parent_order_item_id"

Ref:"person"."id" < "order_item"."recipient_id"

Ref:"location"."id" < "order_item"."destination_bin_location_id"

Ref:"location"."id" < "order_item"."origin_bin_location_id"

Ref:"product_supplier"."id" < "order_item"."product_supplier_id"

Ref:"product_package"."id" < "order_item"."product_package_id"

Ref:"unit_of_measure"."id" < "order_item"."quantity_uom_id"

Ref:"budget_code"."id" < "order_item"."budget_code_id"

Ref:"gl_account"."id" < "order_item"."gl_account_id"

Ref:"order_item"."id" < "order_shipment"."order_item_id"

Ref:"shipment_item"."id" < "order_shipment"."shipment_item_id"

Ref:"party_type"."id" < "party"."party_type_id"

Ref:"location"."id" < "party"."default_location_id"

Ref:"party"."id" < "party_role"."party_id"

Ref:"person"."id" < "picklist"."picker_id"

Ref:"user"."id" < "picklist"."created_by_id"

Ref:"user"."id" < "picklist"."updated_by_id"

Ref:"requisition"."id" < "picklist"."requisition_id"

Ref:"picklist"."id" < "picklist_item"."picklist_id"

Ref:"inventory_item"."id" < "picklist_item"."inventory_item_id"

Ref:"user"."id" < "picklist_item"."created_by_id"

Ref:"user"."id" < "picklist_item"."updated_by_id"

Ref:"requisition_item"."id" < "picklist_item"."requisition_item_id"

Ref:"location"."id" < "picklist_item"."bin_location_id"

Ref:"user"."id" < "preference_type"."created_by_id"

Ref:"user"."id" < "preference_type"."updated_by_id"

Ref:"category"."id" < "product"."category_id"

Ref:"user"."id" < "product"."created_by_id"

Ref:"user"."id" < "product"."updated_by_id"

Ref:"unit_of_measure"."id" < "product"."default_uom_id"

Ref:"product_type"."id" < "product"."product_type_id"

Ref:"gl_account"."id" < "product"."gl_account_id"

Ref:"product"."id" < "product_association"."product_id"

Ref:"product"."id" < "product_association"."associated_product_id"

Ref:"attribute"."id" < "product_attribute"."attribute_id"

Ref:"product"."id" < "product_attribute"."product_id"

Ref:"unit_of_measure"."id" < "product_attribute"."unit_of_measure_id"

Ref:"product_supplier"."id" < "product_attribute"."product_supplier_id"

Ref:"location"."id" < "product_availability"."bin_location_id"

Ref:"inventory_item"."id" < "product_availability"."inventory_item_id"

Ref:"location"."id" < "product_availability"."location_id"

Ref:"product"."id" < "product_availability"."product_id"

Ref:"product"."id" < "product_catalog_item"."product_id"

Ref:"product_catalog"."id" < "product_catalog_item"."product_catalog_id"

Ref:"category"."id" < "product_category"."category_id"

Ref:"product"."id" < "product_component"."assembly_product_id"

Ref:"product"."id" < "product_component"."component_product_id"

Ref:"unit_of_measure"."id" < "product_component"."unit_of_measure_id"

Ref:"product"."id" < "product_dimension"."product_id"

Ref:"product"."id" < "product_document"."product_id"

Ref:"document"."id" < "product_document"."document_id"

Ref:"category"."id" < "product_group"."category_id"

Ref:"product_group"."id" < "product_group_product"."product_group_id"

Ref:"product"."id" < "product_group_product"."product_id"

Ref:"unit_of_measure"."id" < "product_package"."uom_id"

Ref:"product"."id" < "product_package"."product_id"

Ref:"user"."id" < "product_package"."created_by_id"

Ref:"user"."id" < "product_package"."updated_by_id"

Ref:"product_supplier"."id" < "product_package"."product_supplier_id"

Ref:"unit_of_measure"."id" < "product_price"."currency_id"

Ref:"user"."id" < "product_price"."created_by_id"

Ref:"user"."id" < "product_price"."updated_by_id"

Ref:"party"."id" < "product_supplier"."manufacturer_id"

Ref:"product"."id" < "product_supplier"."product_id"

Ref:"party"."id" < "product_supplier"."supplier_id"

Ref:"unit_of_measure"."id" < "product_supplier"."unit_of_measure_id"

Ref:"product_supplier"."id" < "product_supplier_preference"."product_supplier_id"

Ref:"party"."id" < "product_supplier_preference"."destination_party_id"

Ref:"preference_type"."id" < "product_supplier_preference"."preference_type_id"

Ref:"user"."id" < "product_supplier_preference"."created_by_id"

Ref:"user"."id" < "product_supplier_preference"."updated_by_id"

Ref:"product"."id" < "product_tag"."product_id"

Ref:"tag"."id" < "product_tag"."tag_id"

Ref:"product_type"."id" < "product_type_displayed_fields"."product_type_id"

Ref:"product_type"."id" < "product_type_required_fields"."product_type_id"

Ref:"product_type"."id" < "product_type_supported_activities"."product_type_id"

Ref:"person"."id" < "receipt"."recipient_id"

Ref:"shipment"."id" < "receipt"."shipment_id"

Ref:"product"."id" < "receipt_item"."product_id"

Ref:"receipt"."id" < "receipt_item"."receipt_id"

Ref:"person"."id" < "receipt_item"."recipient_id"

Ref:"shipment_item"."id" < "receipt_item"."shipment_item_id"

Ref:"inventory_item"."id" < "receipt_item"."inventory_item_id"

Ref:"location"."id" < "receipt_item"."bin_location_id"

Ref:"reference_number_type"."id" < "reference_number"."reference_number_type_id"

Ref:"location"."id" < "requisition"."destination_id"

Ref:"location"."id" < "requisition"."origin_id"

Ref:"person"."id" < "requisition"."recipient_id"

Ref:"person"."id" < "requisition"."requested_by_id"

Ref:"fulfillment"."id" < "requisition"."fulfillment_id"

Ref:"user"."id" < "requisition"."created_by_id"

Ref:"user"."id" < "requisition"."updated_by_id"

Ref:"person"."id" < "requisition"."verified_by_id"

Ref:"person"."id" < "requisition"."reviewed_by_id"

Ref:"person"."id" < "requisition"."delivered_by_id"

Ref:"person"."id" < "requisition"."received_by_id"

Ref:"person"."id" < "requisition"."checked_by_id"

Ref:"person"."id" < "requisition"."issued_by_id"

Ref:"requisition"."id" < "requisition"."requisition_template_id"

Ref:"category"."id" < "requisition_item"."category_id"

Ref:"inventory_item"."id" < "requisition_item"."inventory_item_id"

Ref:"product"."id" < "requisition_item"."product_id"

Ref:"requisition"."id" < "requisition_item"."requisition_id"

Ref:"user"."id" < "requisition_item"."requested_by_id"

Ref:"person"."id" < "requisition_item"."requested_by_id"

Ref:"product_group"."id" < "requisition_item"."product_group_id"

Ref:"person"."id" < "requisition_item"."recipient_id"

Ref:"requisition_item"."id" < "requisition_item"."parent_requisition_item_id"

Ref:"product_package"."id" < "requisition_item"."product_package_id"

Ref:"user"."id" < "requisition_item"."created_by_id"

Ref:"user"."id" < "requisition_item"."updated_by_id"

Ref:"requisition_item"."id" < "requisition_item"."substitution_item_id"

Ref:"requisition_item"."id" < "requisition_item"."modification_item_id"

Ref:"person"."id" < "shipment"."carrier_id"

Ref:"location"."id" < "shipment"."destination_id"

Ref:"donor"."id" < "shipment"."donor_id"

Ref:"location"."id" < "shipment"."origin_id"

Ref:"person"."id" < "shipment"."recipient_id"

Ref:"shipment_method"."id" < "shipment"."shipment_method_id"

Ref:"shipment_type"."id" < "shipment"."shipment_type_id"

Ref:"event"."id" < "shipment"."current_event_id"

Ref:"user"."id" < "shipment"."created_by_id"

Ref:"user"."id" < "shipment"."updated_by_id"

Ref:"requisition"."id" < "shipment"."requisition_id"

Ref:"comment"."id" < "shipment_comment"."comment_id"

Ref:"document"."id" < "shipment_document"."document_id"

Ref:"shipment"."id" < "shipment_event"."shipment_events_id"

Ref:"event"."id" < "shipment_event"."event_id"

Ref:"invoice_item"."id" < "shipment_invoice"."invoice_item_id"

Ref:"shipment_item"."id" < "shipment_invoice"."shipment_item_id"

Ref:"container"."id" < "shipment_item"."container_id"

Ref:"donor"."id" < "shipment_item"."donor_id"

Ref:"product"."id" < "shipment_item"."product_id"

Ref:"person"."id" < "shipment_item"."recipient_id"

Ref:"shipment"."id" < "shipment_item"."shipment_id"

Ref:"inventory_item"."id" < "shipment_item"."inventory_item_id"

Ref:"location"."id" < "shipment_item"."bin_location_id"

Ref:"requisition_item"."id" < "shipment_item"."requisition_item_id"

Ref:"shipper_service"."id" < "shipment_method"."shipper_service_id"

Ref:"shipper"."id" < "shipment_method"."shipper_id"

Ref:"reference_number"."id" < "shipment_reference_number"."reference_number_id"

Ref:"shipment_type"."id" < "shipment_workflow"."shipment_type_id"

Ref:"container_type"."id" < "shipment_workflow_container_type"."container_type_id"

Ref:"shipment_workflow"."id" < "shipment_workflow_document"."shipment_workflow_id"

Ref:"document"."id" < "shipment_workflow_document"."document_id"

Ref:"reference_number_type"."id" < "shipment_workflow_reference_number_type"."reference_number_type_id"

Ref:"shipper"."id" < "shipper_service"."shipper_id"

Ref:"product"."id" < "synonym"."product_id"

Ref:"user"."id" < "synonym"."created_by_id"

Ref:"user"."id" < "synonym"."updated_by_id"

Ref:"user"."id" < "tag"."created_by_id"

Ref:"user"."id" < "tag"."updated_by_id"

Ref:"user"."id" < "transaction"."created_by_id"

Ref:"location"."id" < "transaction"."destination_id"

Ref:"inventory"."id" < "transaction"."inventory_id"

Ref:"location"."id" < "transaction"."source_id"

Ref:"transaction_type"."id" < "transaction"."transaction_type_id"

Ref:"user"."id" < "transaction"."confirmed_by_id"

Ref:"shipment"."id" < "transaction"."incoming_shipment_id"

Ref:"shipment"."id" < "transaction"."outgoing_shipment_id"

Ref:"user"."id" < "transaction"."updated_by_id"

Ref:"requisition"."id" < "transaction"."requisition_id"

Ref:"order"."id" < "transaction"."order_id"

Ref:"receipt"."id" < "transaction"."receipt_id"

Ref:"inventory_item"."id" < "transaction_entry"."inventory_item_id"

Ref:"transaction"."id" < "transaction_entry"."transaction_id"

Ref:"location"."id" < "transaction_entry"."bin_location_id"

Ref:"product"."id" < "transaction_entry"."product_id"

Ref:"location_dimension"."id" < "transaction_fact"."location_key_id"

Ref:"lot_dimension"."id" < "transaction_fact"."lot_key_id"

Ref:"product_dimension"."id" < "transaction_fact"."product_key_id"

Ref:"date_dimension"."id" < "transaction_fact"."transaction_date_key_id"

Ref:"transaction_type_dimension"."id" < "transaction_fact"."transaction_type_key_id"

Ref:"unit_of_measure_class"."id" < "unit_of_measure"."uom_class_id"

Ref:"user"."id" < "unit_of_measure"."created_by_id"

Ref:"user"."id" < "unit_of_measure"."updated_by_id"

Ref:"unit_of_measure"."id" < "unit_of_measure_class"."base_uom_id"

Ref:"user"."id" < "unit_of_measure_class"."created_by_id"

Ref:"user"."id" < "unit_of_measure_class"."updated_by_id"

Ref:"unit_of_measure"."id" < "unit_of_measure_conversion"."from_unit_of_measure_id"

Ref:"unit_of_measure"."id" < "unit_of_measure_conversion"."to_unit_of_measure_id"

Ref:"user"."id" < "user"."manager_id"

Ref:"location"."id" < "user"."warehouse_id"

Ref:"user"."id" < "user_role"."user_id"

Ref:"role"."id" < "user_role"."role_id"
