const LOCATION_MOCKS = [
  'AlGhanem Group [Supplier]',
  'Amazon [Supplier]',
  'Bangalore 011 [Depot]',
  'Bangalore- 20 Tech [Distributor]',
  'Bangalore-Titan [Supplier]',
  'Bangalore-Vijayanagar [Warehouse]',
  'Belonia foods [Supplier]',
  'Canada [Warehouse]',
  'CCS [Depot]',
  'CDMX [Cliente]',
  'China [Supplier]',
  'CHT [Installation]',
  'Client Test [Cliente]',
  'Corona CA [Depot]',
  'DELHI - BADARPUR [Book Wahrehouse]',
  'DELHI - EAST [Book Wahrehouse]',
  'DELHI - IG AIRPORT [Book Wahrehouse]',
  'DELHI - NORTH [Book Wahrehouse]',
  'DELHI - SOUTH [Book Wahrehouse]',
  'East End SH Clinic [SH Clinic]',
  'East Medical Facility [Depot]',
  'East Pharmacy Depot [Depot]',
  'East Pharmacy Supplier [Supplier]',
  'EXCELINDO [Supplier]',
  'FARIDABAD [Depot]',
  'Florida [Depot]',
  'GBAC [Installation]',
  'Gujarat [Warehouse]',
  'Harbour [Depot]',
  'HO-JKT [HO]',
  'Importaciones VEN [Cliente]',
  'INDIA - NOIDA [Book Wahrehouse]',
  'ISAAC [Cliente]',
  'LC 002 [SH Clinic]',
  'MOM [Depot]',
  'Monitors [Book Wahrehouse]',
  'New location [Depot]',
  'OpenBoxes HQ [Depot]',
  'Palletized [Depot]',
  'PHH [Installation]',
  'PNC [Supplier]',
  'Porto [Book Wahrehouse]',
  'Principal [Principal]',
  'RIM India Pvt Ltd [Warehouse]',
  'Rivercess [Depot]',
  'Sambas - Kalbar [Supplier]',
  'Sepang Air Port [Book Wahrehouse]',
  'SNET [Supplier]',
  'SO MEDAN [SO]',
  'SO SURABAYA [SO]',
  'Toulouse [Supplier]',
  'Zwedru [Installation]',
  'Головной офис [Depot]',
];

const USERNAMES_MOCKS = ['Julian Benson',
  'Alyssa Chandler',
  'Diana Sharp',
  'Caleb Ramirez',
  'Sonia Rios',
  'Wilbur Moran',
  'Nadine Bowen',
  'Bradford Ingram',
  'Johnnie Rodriquez',
  'Kim Dennis',
];

const STOCK_LIST_MOCKS = [
  { value: '', label: ' ' },
  { value: '1', label: '1st Stock List' },
  { value: '2', label: '2nd Stock List' },
  { value: '3', label: '3rd Stock List' },
  { value: '4', label: '4th Stock List' },
];

export {
  LOCATION_MOCKS,
  USERNAMES_MOCKS,
  STOCK_LIST_MOCKS,
};
