export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const FETCH_REASONCODES = 'FETCH_REASONCODES';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_SESSION_INFO = 'FETCH_SESSION_INFO';
export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const TRANSLATIONS_FETCHED = 'TRANSLATIONS_FETCHED';
