export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

export const TOGGLE_LOCATION_CHOOSER = 'TOGGLE_LOCATION_CHOOSER';
export const TOGGLE_USER_ACTION_MENU = 'TOGGLE_USER_ACTION_MENU';

export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_REASONCODES = 'FETCH_REASONCODES';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_SESSION_INFO = 'FETCH_SESSION_INFO';
export const FETCH_MENU_CONFIG = 'FETCH_MENU_CONFIG';
export const CHANGE_CURRENT_LOCATION = 'CHANGE_CURRENT_LOCATION';
export const TRANSLATIONS_FETCHED = 'TRANSLATIONS_FETCHED';
export const CHANGE_CURRENT_LOCALE = 'CHANGE_CURRENT_LOCALE';

export const FETCH_GRAPHS = 'FETCH_GRAPHS';
export const RESET_INDICATORS = 'RESET_INDICATORS';
export const FETCH_NUMBERS = 'FETCH_NUMBERS';
export const REMOVE_FROM_INDICATORS = 'REMOVE_FROM_INDICATORS';
export const ADD_TO_INDICATORS = 'ADD_TO_INDICATORS';
export const REORDER_INDICATORS = 'REORDER_INDICATORS';
export const FETCH_CONFIG = 'FETCH_CONFIG';
export const SET_ACTIVE_CONFIG = 'SET_ACTIVE_CONFIG';

export const UPDATE_BREADCRUMBS_PARAMS = 'UPDATE_BREADCRUMBS_PARAMS';
export const FETCH_BREADCRUMBS_CONFIG = 'FETCH_BREADCRUMBS_CONFIG';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
