import axios from 'axios';

import {
  VALIDATE_LOT,
} from 'api/urls';

export default {
  // Invalid lots should be caught manually to display modals with the information
  // about updating expiration date across all depots in the system without
  // error message generated by our error handling
  validateLot: data => axios.post(VALIDATE_LOT, data),
};
