export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export const FETCH_PRODUCTS_CATEGORIES = 'FETCH_PRODUCT_CATEGORIES';
export const FETCH_PRODUCTS_CATALOGS = 'FETCH_PRODUCTS_CATALOGS';
export const FETCH_PRODUCTS_TAGS = 'FETCH_PRODUCTS_TAGS';

