package org.pih.warehouse.core;

public enum ActivityCode {
	
	MANAGE_INVENTORY('MANAGE_INVENTORY'),
	PLACE_ORDER('PLACE_ORDER'),
	PLACE_REQUEST('PLACE_REQUEST'),
	PROCESS_ORDER('PROCESS_ORDER'),
	PROCESS_REQUEST('PROCESS_REQUEST'),
	SEND_STOCK('SEND_STOCK'),
	RECEIVE_STOCK('RECEIVE_STOCK'),
	EXTERNAL('EXTERNAL')
	
	final String id
	
	ActivityCode(String id) { this.id = id }
	
	static list() {
		[MANAGE_INVENTORY, PLACE_ORDER, PLACE_REQUEST, PROCESS_ORDER, PROCESS_REQUEST, SEND_STOCK, RECEIVE_STOCK, EXTERNAL]
	}
}
