package org.pih.warehouse.stocklist

class StocklistManagementController {
    def index() {
        // This template is generated by webpack during application start
        def contextPath = grailsApplication.config.server.contextPath
        render(template: "/common/react", model: [contextPath: contextPath != '/' ? contextPath : ''])
    }
}
