package org.pih.warehouse.stocklist

class StocklistManagementController {
    def index = {
        // This template is generated by webpack during application start
        render(template: "/common/react")
    }
}
