package org.pih.warehouse.partialReceiving

import org.pih.warehouse.shipping.Shipment

class PartialReceivingController {

	def receiptService

	def index = {
		redirect(action: "create")
	}

	// This template is generated by webpack during application start
	def create = {
		render(template: "/partialReceiving/create")
	}

	def rollbackLastReceipt = {
		Shipment shipment = Shipment.get(params.id)

		if (shipment) {
			receiptService.rollbackLastReceipt(shipment)
		}

		redirect(controller: "stockMovement", action: "show", id: shipment?.requisition?.id)
	}
}
