package org.pih.warehouse.partialReceiving

class PartialReceivingController {
	def index = {
		redirect(action: "create")
	}

	// This template is generated by webpack during application start
	def create = {
		render(template: "/partialReceiving/create")
	}
}
