package org.pih.warehouse.putaway

import com.google.zxing.BarcodeFormat
import grails.converters.JSON
import grails.gorm.transactions.Transactional
import org.grails.web.json.JSONObject
import org.pih.warehouse.api.Putaway
import org.pih.warehouse.api.PutawayItem
import org.pih.warehouse.api.PutawayTaskStatus
import org.pih.warehouse.api.putaway.SearchPutawayTaskCommand
import org.pih.warehouse.core.Location
import org.pih.warehouse.core.Person
import org.pih.warehouse.inventory.InventoryLevel
import org.pih.warehouse.order.Order

@Transactional
class PutawayController {

    def barcodeService
    def productAvailabilityService
    PutawayService putawayService
    PutawayTaskService putawayTaskService

    def index() {
        redirect(action: "create")
    }

    def list() {
        redirect(action: "create")
    }

    // This template is generated by webpack during application start
    def create() {
        render(view: "/common/react")
    }

    @Transactional(readOnly = true)
    def show(String id) {
        Order order = Order.get(id)
        if (!order) {
            flash.message = "Order not found with id ${id}"
            redirect(controller: "order", action: "list")
            return
        }
        [orderInstance: order]
    }

    def putawayTasks(String id) {
        Order order = Order.get(id)
        if (!order) {
            render status: 404, text: "Order not found"
            return
        }

        def command = new SearchPutawayTaskCommand(facility: order.destination, order: order)
        List<PutawayTask> tasks = putawayTaskService.search(command, params)

        render(template: "putawayTasks", model: [orderInstance: order, putawayTasks: tasks])
    }

    def rollback(String id) {
        Putaway putaway = putawayService.getPutaway(id)
        putawayService.rollbackPutaway(putaway)

        flash.message = "Rollback was completed successfully for putaway ${putaway.putawayNumber}"

        redirect(controller: "putaway", action: "show", id: id)
    }

    def rollbackAndDelete(String id) {
        Putaway putaway = putawayService.getPutaway(id)
        putawayService.rollbackAndDelete(putaway)

        flash.message = "Putaway has been deleted successfully for putaway ${putaway.putawayNumber}"

        redirect(controller: "order", action: "list", params: [orderType: "PUTAWAY_ORDER", status: "PENDING"])
    }

    @Transactional(readOnly = true)
    def putawayTaskFormDialog(String id) {
        PutawayTask task = putawayTaskService.get(id)
        if (!task) {
            render status: 404, text: "Putaway task not found"
            return
        }
        render(template: "putawayTaskFormDialog", model: [task: task, facility: task.facility])
    }

    def savePutawayTask() {
        try {
            PutawayTask task = putawayTaskService.get(params['task.id'])
            if (!task) {
                response.status = 404
                render([errorMessage: "Putaway task not found"] as JSON)
                return
            }
            if (params.status) {
                task.status = params.status as PutawayTaskStatus
            }
            if (params.containsKey('destination.id')) {
                task.destination = params['destination.id'] ? Location.get(params['destination.id']) : null
            }
            if (params.containsKey('container.id')) {
                task.container = params['container.id'] ? Location.get(params['container.id']) : null
            }
            if (params.containsKey('assignee.id')) {
                task.assignee = params['assignee.id'] ? Person.get(params['assignee.id']) : null
            }
            task.dateStarted = parseDateStruct(params, 'dateStarted')
            task.dateCompleted = parseDateStruct(params, 'dateCompleted')
            putawayTaskService.save(task)
            render(status: 200, text: "OK")
        } catch (Exception e) {
            log.error("Error saving putaway task", e)
            response.status = 500
            render([errorMessage: e.message] as JSON)
        }
    }

    @Transactional(readOnly = true)
    def putawayTaskTicket(String id) {
        PutawayTask task = putawayTaskService.get(id)
        if (!task) {
            flash.message = "Putaway task not found"
            redirect(action: "show", id: id)
            return
        }
        render(template: "putawayTaskTicket", model: [task: task, pdfMode: false])
    }

    @Transactional(readOnly = true)
    def downloadPutawayTaskTicket(String id) {
        PutawayTask task = putawayTaskService.get(id)
        if (!task) {
            render status: 404, text: "Putaway task not found"
            return
        }

        def productCodeBytes = generateBarcode(task.product?.productCode)
        def destinationBytes = generateBarcode(task.destination?.locationNumber ?: task.destination?.name)
        def containerBytes = generateBarcode(task.container?.locationNumber ?: task.container?.name)

        renderPdf(
                template: "putawayTaskTicket",
                model: [task: task, pdfMode: true,
                        productCodeBytes: productCodeBytes,
                        destinationBytes: destinationBytes,
                        containerBytes: containerBytes],
                filename: "PutawayTask-${task.identifier ?: task.id}.pdf"
        )
    }

    private byte[] generateBarcode(String data) {
        if (!data) return null
        def baos = new ByteArrayOutputStream()
        barcodeService.renderImage(baos, data, 200, 50, BarcodeFormat.CODE_128)
        return baos.toByteArray()
    }

    def generatePdf() {
        log.info "Params " + params

        Putaway putaway
        JSONObject jsonObject

        if (request.method == "POST") {
            jsonObject = request.JSON
        } else if (params.id) {
            Order order = Order.get(params.id)
            putaway = Putaway.createFromOrder(order)
            putaway.sortBy = params.sortBy
            putaway.putawayItems.each { PutawayItem putawayItem ->
                putawayItem.availableItems =
                        productAvailabilityService.getAllAvailableBinLocations(putawayItem.currentFacility, putawayItem.product?.id)
                putawayItem.inventoryLevel = InventoryLevel.findByProductAndInventory(putawayItem.product, putaway.origin.inventory)
            }
            jsonObject = new JSONObject(putaway.toJson())
        }

        renderPdf(
                template: "/putaway/print",
                model: [jsonObject: jsonObject],
                filename: "Putaway ${putaway?.putawayNumber}.pdf"
        )
    }

    private Date parseDateStruct(def params, String prefix) {
        if (params["${prefix}"] != 'struct' || !params["${prefix}_year"]) {
            return null
        }
        Calendar cal = Calendar.instance
        cal.clear()
        cal.set(
            params.int("${prefix}_year"),
            params.int("${prefix}_month") - 1,
            params.int("${prefix}_day"),
            params.int("${prefix}_hour") ?: 0,
            params.int("${prefix}_minute") ?: 0,
            0
        )
        return cal.time
    }
}
