package org.pih.warehouse.api.receiving.v2

import javax.validation.Valid

import org.pih.warehouse.api.BaseApiController
import org.pih.warehouse.core.dtos.BatchCommandUtils
import org.pih.warehouse.receiving.ReceiptDto
import org.pih.warehouse.receiving.ReceiptSaveResponseDto
import org.pih.warehouse.receiving.ShipmentReceivingSummaryCommand
import org.pih.warehouse.receiving.ShipmentReceivingSummaryDto
import org.pih.warehouse.receiving.ReceiptItemsBatchRequest

class ReceiptApiController extends BaseApiController {

    ReceiptV2Service receiptV2Service

    def view() {
        // This template is generated by webpack during application start
        render(view: "/common/react")
    }

    def start() {
        ReceiptDto receipt = receiptV2Service.startReceipt(params.shipmentId)
        renderResponse(data: receipt, status: 201)
    }

    /**
     * List all receipts (and their receipt items) that are associated with a shipment.
     */
    def listShipmentReceipts(String shipmentId) {
        List<ReceiptDto> receipts = receiptV2Service.listShipmentReceipts(shipmentId)
        renderResponse(receipts)
    }

    /**
     * Fetches an overview of a shipment's current state of receiving.
     */
    def getShipmentReceivingSummary(@Valid ShipmentReceivingSummaryCommand command) {
        ShipmentReceivingSummaryDto summary = receiptV2Service.getShipmentReceivingSummary(command)
        renderResponse(summary)
    }

    def updateItemsBatch(ReceiptItemsBatchRequest request) {
        BatchCommandUtils.validateBatch(request, "itemsToSave")

        ReceiptSaveResponseDto response = receiptV2Service.updateItemsBatch(params.receiptId, request)
        renderResponse(response)
    }
}
