name: dbdocs

on:
  # Update the docs whenever a new database change is pushed to the develop branch. As such, the docs will always
  # contain the 'latest' database state (instead of being in sync with 'main' / the latest stable release).
  push:
    branches: [ develop ]
    paths: [ 'grails-app/migrations/**' ]

  # Also allow the build to be run manually in case we need to trigger a release of the docs ourselves.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      - name: Update dbdocs project
        env:
          DBDOCS_TOKEN: ${{ secrets.DBDOCS_TOKEN }}
        run: dbdocs build ./openboxes.dbml
