name: Auto-format Pull Requests

on:
  # Use pull_request_target instead of pull_request because we want this to run on PRs from forks. Simply allowing
  # actions to run can be insecure, hence why we require approval before running actions in a PR from a fork.
  pull_request_target:
    types: [opened, synchronize]

jobs:
  pr-formatter:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # See .github/labeler.yml for config
      - name: Label Pull Request
        uses: actions/labeler@v5
