name: Auto-format Pull Requests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-formatter:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # See .github/labeler.yml for config
      - name: Label Pull Request
        uses: actions/labeler@v5
